Allowed more attributes on buttons
infinum/eightshift-libs pull request #103
Opened 2020-11-30 21:00 UTC by gabriel-glo

Allowed class, id and type attributes to buttons rendered by `Components::render`

This broke the hamburger and drawer components as hamburger button didn't have class attribute.

2020-11-30 22:32 UTC, gabriel-glo commented
@dingo-d All these test failed because they tried to access sniff called Infinum and I think you renamed that.
Do these tests need to be updated with the name change to Eightshift?

2020-12-01 07:39 UTC, IvanGrginovInf requested changes

2020-12-01 07:39 UTC, IvanGrginovInf commented on src/View/AbstractEscapedView.php
> +      'onClick' => true,
You're mixing tabs & spaces with the rest of the tags here.

2020-12-01 08:09 UTC, gabriel-glo commented on src/View/AbstractEscapedView.php
> +      'onClick' => true,
Didn't even notice. I need to change my editor settings.

2020-12-01 08:19 UTC, iruzevic approved these changes

2020-12-01 08:21 UTC, volfkarlo approved these changes

2020-12-01 08:21 UTC, IvanGrginovInf approved these changes

2020-12-01 08:22 UTC, gabriel-glo commented
Do you think we need to add even more attributes for the button element?

2020-12-01 13:00 UTC, merged