Chain replace cli commands
infinum/eightshift-libs pull request #108
Opened 2020-12-04 07:52 UTC by dingo-d

I noticed that we are always doing things step by step by step. And I thought to myself: 

_Self, wouldn't it be cooler if you could just chain these methods? Like the cool devs in Laravel and Symfony are doing?_

Sure enough, turns that you can do that.

> But why would you do that??

Because I can 😆  (evil laugh lol).

Not sure about the performance gain, but it just looks better.

```php
public function __invoke(array $args, array $assocArgs) // phpcs:ignore
{
    $className = $this->getClassShortName();

    // Read the template contents and replace the placeholders with provided variables.
    $class = $this->getExampleTemplate(__DIR__, $className);

    // Replace stuff in file.
    $class = $this->renameClassName($className, $class);

    $class = $this->renameNamespace($assocArgs, $class);

    $class = $this->renameUse($assocArgs, $class);

    // Output final class to new file/folder and finish.
    $this->outputWrite(static::OUTPUT_DIR, $className, $class, $assocArgs);
}
```

vs 

```php
public function __invoke(array $args, array $assocArgs) // phpcs:ignore
{
    $className = $this->getClassShortName();

    // Read the template contents and replace the placeholders with provided variables.
    $this->getExampleTemplate(__DIR__, $className)
        ->renameClassName($className)
        ->renameNamespace($assocArgs)
        ->renameUse($assocArgs)
        ->outputWrite(static::OUTPUT_DIR, $className, $assocArgs);
}
```

The commands just flow one after another, doing their thing. Beautiful. Clean. Efficient.

Ok, not 100% sure about the efficiency, but when I ran this command it was darn fast. Not sure if that was the rush of this newfound power or something to do with the fact I'm no longer overwriting the variable all the time and passing it around, and instead just writing to a member variable. I'd have to profile these calls and check (I wrote it as a to do in my little book).

**This is still a WIP**. All the other renaming CLI classes need to be changed and maybe some other helper methods.

This PR should be reviewed by commits. I anticipate it will be a bit larger, as every CLI class will have to be changed, so it's going to be easier to review it one commit at a time.

Also, I've put most of the commands back to the abstract class. No real need for them to be in the trait, as they are not reused anywhere 🤷‍♂️  Except the error one, that's actually used all over the place.

2020-12-04 07:52 UTC, iruzevic approved these changes

2020-12-05 11:09 UTC, iruzevic requested changes

2020-12-05 11:09 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +		$class = explode('_', str_replace('-', '_', str_replace(' ', '_', strtolower($fileName))));
there has been some changes on this files. can you please check this PR and implement the changes to your branch ?

https://github.com/infinum/eightshift-libs/pull/106/files

2020-12-05 11:11 UTC, IvanGrginovInf approved these changes

2020-12-05 11:13 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +		$class = explode('_', str_replace('-', '_', str_replace(' ', '_', strtolower($fileName))));
Hmmm, if the PR was merged to branch 3.0.0 I should have picked those changes up because I rebased. Unless you made some changes 10 min ago 😂 

Will look at the diff.

2020-12-05 11:23 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +		$class = explode('_', str_replace('-', '_', str_replace(' ', '_', strtolower($fileName))));
Ok, missed this because this was changed in helpers, not the abstract class. 👍

2020-12-05 11:42 UTC, iruzevic approved these changes

2020-12-07 07:37 UTC, volfkarlo approved these changes

2020-12-07 07:37 UTC, volfkarlo commented on tests/Helpers/ComponentHelpersTest.php
> +
I assume this many empty lines are here because of WIP.

2020-12-07 08:07 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +
Good catch!

2020-12-16 13:42 UTC, iruzevic approved these changes

2020-12-16 13:43 UTC, merged