Update form allowed html list
infinum/eightshift-libs pull request #122
Opened 2020-12-16 23:06 UTC by gabriel-glo

Allow `selected` attribute to the `option` element
Allow `checked` and `disabled` attribute to the `input` element

2020-12-17 05:29 UTC, iruzevic approved these changes

2020-12-17 09:13 UTC, kmaric69 approved these changes

2020-12-17 09:26 UTC, dingo-d approved these changes

2020-12-22 13:10 UTC, dingo-d commented
`meta` tag should also be added, with the options, so that the head component isn't stripped away (that breaks the responsive)

2020-12-22 13:10 UTC, dingo-d requested changes
meta tag should be added

2020-12-23 08:32 UTC, iruzevic approved these changes

2020-12-23 08:32 UTC, merged