Release v3.1.0
infinum/eightshift-libs pull request #133
Opened 2021-01-13 09:16 UTC by szepeviktor

Let's run CI!

2021-01-13 10:39 UTC, IvanGrginovInf approved these changes

2021-01-13 10:44 UTC, iruzevic requested changes
@dingo-d Is this ready to be merged to develop?

2021-01-13 11:39 UTC, dingo-d commented
@iruzevic I wouldn't merge it just yet. Let's up the coverage a bit, fix all the potential bugs and issues first, and then we can merge to develop.

2021-01-13 12:05 UTC, szepeviktor commented
Please put `.phpunit.result.cache` into gitignore and remove it from git.

2021-01-14 10:56 UTC, szepeviktor commented
Change `CliInterface` return typehint to `self` in `src/Cli/AbstractCli.php`

2021-01-15 11:01 UTC, szepeviktor commented on src/Blocks/BlockVariationCli.php
> +				$class->renameProjectName($assocArgs)
Hello! 👋 
I'm the method `renameProjectName`.
I want to be called `changeProjectName` but my parents resist.

2021-01-15 11:10 UTC, dingo-d commented on src/Blocks/BlockVariationCli.php
> +				$class->renameProjectName($assocArgs)
Parents don't really have issues with the naming or changing them tbh 😂 

Why would you rename this method? I mean, it's doing the renaming after all, no?

2021-01-15 11:16 UTC, szepeviktor commented on src/Blocks/BlockVariationCli.php
> +				$class->renameProjectName($assocArgs)
Changing/Replacing placeholders with actual values are called "change" or "replace".

2021-01-15 11:28 UTC, IvanGrginovInf approved these changes

2021-01-15 11:41 UTC, dingo-d commented on src/Blocks/BlockVariationCli.php
> +				$class->renameProjectName($assocArgs)
Or renaming from the default, placeholder, name to something other 😉

2021-02-24 09:45 UTC, dingo-d commented
There is a problem with using `setup_theme` CLI in this branch. It copies the files that do not exist, so that will have to be addressed.

2021-02-24 21:12 UTC, szepeviktor commented on .github/workflows/ci.yml
> -       run: composer analyze | cs2pr
@dingo-d PHPStan includes automatic output for GHA

2021-02-24 21:13 UTC, szepeviktor commented on .github/workflows/ci.yml
> -        run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}- | cs2pr
```yaml
run: composer standards:check -- -q --runtime-set testVersion ${{ matrix.php }}- --report=checkstyle | cs2pr
```

2021-02-25 07:56 UTC, dingo-d commented on .github/workflows/ci.yml
> -        run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}- | cs2pr
I tried running act with this or with XML but still I get an error. I'll leave it removed for now.

2021-02-25 09:00 UTC, szepeviktor commented on .github/workflows/ci.yml
> -        run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}- | cs2pr
Maybe `-q` was missing.

2021-03-10 08:18 UTC, dingo-d commented
@iruzevic there seems to be one phpstan error that was introduced 🙈

2021-03-31 14:59 UTC, closed without merging

2021-03-31 14:59 UTC, iruzevic commented
We will open a PR when we are ready to merge