updating readme
infinum/eightshift-libs pull request #137
Opened 2021-01-15 23:40 UTC by iruzevic

- I have updated the readme as described in this ticket https://app.productive.io/1-infinum/projects/18136/tasks/task/1282865?filter=LTE%3D
but haven't added any search and replace. This readme once moved in the project should be changed manually.

I plan to update this to automatic once release/3.1.0 is out

2021-01-16 08:43 UTC, dingo-d requested changes
If you plan on releasing this with 3.1.0, can you rebase to the `release/3.1.0` branch and write tests for it while you're at it? 

That branch has tests, and all the CI checks are passing 🙂

2021-01-16 08:45 UTC, iruzevic commented
Plan is to release it in the next minor version but update the WP-CLI and test in the release/3.1./

2021-01-16 17:48 UTC, dingo-d approved these changes

2021-01-18 08:08 UTC, IvanGrginovInf approved these changes

2021-01-18 08:37 UTC, gabriel-glo approved these changes

2021-01-18 08:48 UTC, merged