WIP: Test
infinum/eightshift-libs pull request #147
Opened 2021-02-25 23:54 UTC by iruzevic

2021-02-25 23:55 UTC, iruzevic commented on tests/Helpers/ComponentHelpersTest.php
> +test('Throws exception if any other argument is passed other than string or array', function () {
@dingo-d Can you please help me why is this failing?

"Call to undefined function esc_html__()"

2021-02-26 08:22 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +error_log( print_r( ( Components::ensureString(0) ), true ) );
Rogue error log. If you want to see what it throws during testing you'll need to put the error log inside the test (or just `print_r` or `var_dump`). I mean the best way is to use the debugger to see what is happening during the test.

2021-02-26 08:26 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +test('Throws exception if any other argument is passed other than string or array', function () {
It shouldn't, seeing how `setupMocks` is called before all tests. Maybe it should be `beforeEach(function() { setupMocks(); });` 🤷🏼‍♂️ 

But anyhow, this case should be covered with the test on line 22. If you look at it closely it will take an arbitrary number of arguments, and test that the type error is thrown, using the `errorStringArguments` dataset, defined in `Arguments.php`.

2021-02-26 08:31 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +test('Throws exception if any other argument is passed other than string or array', function () {
More to the point I just ran the tests and it's the test on line 22 that is faulty. It should be:

```php
test('Throws type exception if wrong argument type is passed to ensureString', function ($argument) {
		Components::ensureString($argument);
	})
	->throws(ComponentException::class)
	->with('errorStringArguments');
```

And I found an edge case. When you have a standard object created using `new class{}`, you get

```bash
• Tests\Helpers\ComponentHelpersTest > Throws type exception if wrong argument type is passed to ensureString with (class@anonymous\/Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/tests/Datasets/Arguments.php:9$1dc Object ())
  Failed asserting that exception of type "Error" matches expected exception "EightshiftLibs\Exception\ComponentException". Message was: "Object of class class@anonymous could not be converted to string" at
/Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/src/Exception/ComponentException.php:33
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/src/Helpers/Components.php:48
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/tests/Helpers/ComponentHelpersTest.php:23
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Factories/TestCaseFactory.php:142
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Concerns/TestCase.php:175
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Support/ExceptionTrace.php:28
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Concerns/TestCase.php:176
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Concerns/TestCase.php:164
  /Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/vendor/pestphp/pest/src/Console/Command.php:130
```

That's because this on-the-fly object in the dataset doesn't have `__toString` magic method. So we found an edge case that should be covered in the code \o/ 🎉  😄

2021-03-03 08:06 UTC, IvanGrginovInf approved these changes

2021-03-03 08:52 UTC, iruzevic commented on tests/Helpers/ComponentHelpersTest.php
> +test('Throws exception if any other argument is passed other than string or array', function () {
fixed

2021-03-03 13:59 UTC, kmaric69 approved these changes

2021-03-03 16:14 UTC, IvanGrginovInf approved these changes

2021-03-03 17:09 UTC, dingo-d commented on src/Exception/ComponentException.php
> +			$output = \esc_html__('Object can\'t be converted to string. Please provide only string or array.', 'eightshift-libs');
```suggestion
			$output = \esc_html__('Object couldn\'t be converted to string. Please provide only string or array.', 'eightshift-libs');
```

We should see what the output of the test is for the `ensureString` if we pass the object with `__toString` magic method in it 😄

2021-03-03 17:22 UTC, dingo-d commented on src/Exception/ComponentException.php
> +			$output = \esc_html__('Object can\'t be converted to string. Please provide only string or array.', 'eightshift-libs');
Probably nothing tho, since the `ensureString` will work only with strings and arrays 🤔

2021-03-03 17:28 UTC, dingo-d commented on src/Helpers/Components.php
> +
This doesn't seem to be covered with tests. Can you write a test for this as well?

2021-03-03 17:30 UTC, dingo-d commented on tests/CiExclude/CiExcludeCliTest.php
> +	$this->assertStringContainsString('eightshift-boilerplate', $generatedExclude);
Try to add an 'unhappy path' value here, like

```php
$this->assertStringNotContainsString('footer.php', $generatedExclude);
```

2021-03-03 17:33 UTC, dingo-d commented on tests/CiExclude/CiExcludeCliTest.php
> +	$generatedExclude = file_get_contents(dirname(__FILE__, 3) . '/cliOutput/ci-exclude.txt');
While this on its own is a good indicator that the file exists, it's a bit fragile. Sure, if it fails, you can say: something's wrong. And that's a good indicator, but we have a method that will test if the file has been created:

```php
test('CiExclude CLI command will correctly copy the ci-exclude file in the custom folder with set arguments', function () {
	$ciexclude = $this->ciexclude;
	$ciexclude([], [
		'root' => './test',
	]);

	// Check the output dir if the generated method is correctly generated.
	$this->assertFileExists(dirname(__FILE__, 3) . '/cliOutput/test/ci-exclude.txt');
});
```

🎉

2021-03-03 17:36 UTC, dingo-d commented on tests/GitIgnore/GitIgnoreCliTest.php
> +	$this->assertStringContainsString('wp-admin', $generatedIgnore);
One unhappy path assertion, please 😄

2021-03-03 17:37 UTC, dingo-d commented on tests/GitIgnore/GitIgnoreCliTest.php
> +	$generatedIgnore = file_get_contents(dirname(__FILE__, 3) . '/cliOutput/test/.gitignore');
Use `assertFileExists` assertion here as well 🙂

2021-03-03 17:38 UTC, dingo-d commented on tests/I18n/I18nCliTest.php
> +	$this->assertStringContainsString('namespace EightshiftLibs\I18n', $generatedMain);
Assertion that something is not in the file 🙏🏼

2021-03-03 17:39 UTC, dingo-d commented on tests/I18n/I18nExampleTest.php
> +	->andReturn('CoolProject', 'projectPath');
Can you just indent this by 1 tab, so it's a bit more readable? Thanks!

2021-03-03 17:39 UTC, dingo-d commented on tests/Login/LoginCliTest.php
> +	$this->assertStringContainsString('namespace EightshiftLibs\Login', $generatedLogin);
Unhappy path

2021-03-03 17:39 UTC, dingo-d commented on tests/Main/MainCliTest.php
> +	$this->assertStringContainsString('namespace EightshiftLibs\Main', $generatedMain);
Unhappy path

2021-03-03 17:40 UTC, dingo-d commented on tests/ModifyAdminAppearance/ModifyAdminAppearanceCliTest.php
> +	$this->assertStringContainsString('namespace EightshiftLibs\ModifyAdminAppearance', $generatedModifyAdminAppearance);
Unhappy path

2021-03-03 17:40 UTC, dingo-d commented on tests/Readme/ReadmeCliTest.php
> +	$this->assertStringContainsString('This is the official repository of the {Project name}.', $generatedExclude);
File exists assertion can be used here

2021-03-03 17:41 UTC, dingo-d commented on tests/Services/ServicesCliTest.php
> +	$this->assertStringContainsString('@package EightshiftBoilerplate\TestFolder\TMP', $generatedMain);
Unhappy path

2021-03-03 17:41 UTC, dingo-d commented on tests/Services/ServicesCliTest.php
> +
File exists assertion can be used here.

2021-03-03 17:41 UTC, dingo-d requested changes
Left some minor comments. There is one weird output in the tests, not sure where this is coming from:

```bash
#!/usr/bin/env sh

set -e

function build() {
	cd 'wp-content/themes/eightshift-boilerplate';
	npm install
	composer install --no-dev
	npm run build
}

build
```

Great job 👍🏼

2021-03-03 21:55 UTC, iruzevic commented on src/Helpers/Components.php
> +
Yes but in the next test batch. I will open an new pr for this

2021-03-03 21:59 UTC, iruzevic commented on tests/CiExclude/CiExcludeCliTest.php
> +	$generatedExclude = file_get_contents(dirname(__FILE__, 3) . '/cliOutput/ci-exclude.txt');
awesome tnx

2021-03-03 22:22 UTC, iruzevic commented
Fixed all

2021-03-04 08:24 UTC, dingo-d commented on tests/ModifyAdminAppearance/ModifyAdminAppearanceExampleTest.php
> +	$this->assertStringContainsString('fresh', $output);
I'd add something like `$this->assertStringNotContainsString('sunrise', $output);` either here or in the above test. Maybe even in the above test to confirm the color scheme is correct in case of a specific env.

2021-03-04 08:25 UTC, dingo-d commented on tests/Services/ServiceExampleTest.php
> +	$this->assertTrue(true);
This is not a valid test 👀

2021-03-04 08:25 UTC, dingo-d commented on src/Helpers/Components.php
> +
Usually, when you add a feature you need to cover it with tests in the same branch 🙈

2021-03-04 11:46 UTC, dingo-d approved these changes

2021-03-04 11:52 UTC, iruzevic commented
💣

2021-03-04 11:52 UTC, merged