Unit tests
infinum/eightshift-libs pull request #150
Opened 2021-03-02 18:25 UTC by gabriel-glo

This is a continuation of #121 where all the tests which I've chosen will be made.

- [ ] Config
- [ ] ThemeOptions
- [ ] View
- [ ]  CustomTaxonomy

2021-03-03 17:51 UTC, dingo-d commented on tests/Config/ConfigCliTest.php
> +	$this->assertStringContainsString('getProjectRoutesVersion', $generatedConfig);
Add one test for the 'unhappy path' like that string doesn't contain some rogue string.

2021-03-03 17:51 UTC, dingo-d commented on tests/ThemeOptions/ThemeOptionsCliTest.php
> +	$this->assertStringContainsString('registerThemeOptions', $generatedMeta);
Unhappy path check.

2021-03-03 17:52 UTC, dingo-d requested changes
Left some small comments, great progress so far 👍🏼

2021-03-11 08:29 UTC, iruzevic approved these changes

2021-03-11 08:51 UTC, dingo-d approved these changes

2021-03-11 22:28 UTC, merged