Rest field tests
infinum/eightshift-libs pull request #151
Opened 2021-03-03 14:44 UTC by IvanGrginovInf

Added Tests:
- [ ] FieldCli
- [ ] FieldExample

Still need to add
- [ ] RouteCli
- [ ] RouteExample

2021-03-03 17:42 UTC, dingo-d commented on tests/Datasets/Arguments.php
> +	[['field_name' => 'Neki Field', 'object_type' => 'custom-post-type']],
English please 😄

2021-03-03 17:42 UTC, dingo-d commented on tests/Datasets/Arguments.php
> +	[['field_name' => 'NekiField']],
⬆️

2021-03-03 17:44 UTC, dingo-d commented on tests/Helpers.php
> +	require_once dirname( __FILE__ ) . '/WpMocks/WP_REST_Server.php';
This file just includes the empty `WP_REST_Server` class. Why not just instantiating it here? You don't need to concern yourself with WordPress functionality in unit tests 😉

2021-03-03 17:45 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$this->assertStringContainsString('rest_ensure_response', $generatedField);
Add one assertion for the 'unhappy path', like that some string is not present in the copied class. In the case the string is copied you'll know you have some weird issues 😄

2021-03-03 17:45 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$full_field_name = "{$this->field->getFileName($fieldNameArguments['field_name'])}Field";
```suggestion
	$fullFieldName = "{$this->field->getFileName($fieldNameArguments['field_name'])}Field";
```

CamelCase

2021-03-03 17:45 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$object_type = $fieldNameArguments['object_type'];
```suggestion
	$objectType = $fieldNameArguments['object_type'];
```

2021-03-03 17:46 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$generatedField = file_get_contents(dirname(__FILE__, 4) . "/cliOutput/src/Rest/Fields/{$full_field_name}.php");
```suggestion
	$generatedField = file_get_contents(dirname(__FILE__, 4) . "/cliOutput/src/Rest/Fields/{$fullFieldName}.php");
```

2021-03-03 17:46 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$this->assertStringContainsString("class {$full_field_name} extends AbstractField implements CallableFieldInterface", $generatedField);
```suggestion
	$this->assertStringContainsString("class {$fullFieldName} extends AbstractField implements CallableFieldInterface", $generatedField);
```

2021-03-03 17:46 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +	$this->assertStringContainsString("return '{$object_type}';", $generatedField);
```suggestion
	$this->assertStringContainsString("return '{$objectType}';", $generatedField);
```

2021-03-03 17:47 UTC, dingo-d commented on tests/Rest/Fields/FieldCliTest.php
> +})->with('errorFieldNameArguments')->throws('exception');
Shouldn't the exception be `Exception::class`, that is the correct exception thrown?

2021-03-03 17:48 UTC, dingo-d commented on tests/Rest/Fields/FieldExampleTest.php
> +	putenv('SIDEAFFECT=');
👍🏼

2021-03-03 17:50 UTC, dingo-d requested changes
Left some comments. Great job 👍🏼

2021-03-10 13:32 UTC, IvanGrginovInf commented on tests/Helpers.php
> +	require_once dirname( __FILE__ ) . '/WpMocks/WP_REST_Server.php';
It's used in `tests/Rest/Fields/FieldExampleTest.php` like so:

```
	$this->field->fieldRegisterCallback(new \WP_REST_Server(), 'attr', new class{}, 'post');
```

That's how I used to do it in Codeception tho I guess here I could just mock the object and instantiate it here (not sure if that's possible tho I'd imagine it is).

2021-03-10 13:35 UTC, IvanGrginovInf commented on tests/Rest/Fields/FieldCliTest.php
> +})->with('errorFieldNameArguments')->throws('exception');
Pest does that already. For example this works (and only catches InvalidArgumentException):

`->throws('InvalidArgumentException');`

But I agree, having it as `Exception::class` is much better, will change!

2021-03-10 14:42 UTC, dingo-d commented on .gitignore
> -.phpunit.result.cache
Why are these two removed?

2021-03-10 16:33 UTC, IvanGrginovInf commented on .gitignore
> -.phpunit.result.cache
@dingo-d Hmm didn't commit that but shouldn't this be gitignored?

2021-03-11 08:52 UTC, dingo-d commented on .gitignore
> -.phpunit.result.cache
Yes, it should be, but I'm not sure why it's marked as deleted 👀

2021-03-11 13:00 UTC, IvanGrginovInf commented on .gitignore
> -.phpunit.result.cache
Ah, now I see. Yeah not sure what happened there, re-added it to gitignore.

2021-03-11 14:19 UTC, dingo-d requested changes
`tests/coverage/*` should be ignored as well in the `.gitignore`

2021-03-11 14:21 UTC, dingo-d commented on tests/Helpers.php
> +	require_once dirname( __FILE__ ) . '/WpMocks/WP_REST_Server.php';
Yeah, mock it on the fly in the test.

2021-03-17 09:59 UTC, dingo-d approved these changes

2021-03-17 10:24 UTC, merged