WIP Test cli part
infinum/eightshift-libs pull request #160
Opened 2021-03-10 14:15 UTC by dingo-d

Testing CLI commands.

2021-03-10 14:17 UTC, IvanGrginovInf commented on tests/Cli/CliInitProjectTest.php
> +	$this->assertEquals('Generates initial setup for WordPress theme project with all files to run a client project, for example: gitignore file for the full WordPress project, continuous integration ex
Maybe it's a bit too much? Because now the test is coupled to the documentation copy being exactly like this. (i.e. if we change a word / fix a typo in that, it will break this test). Or is that maybe the intention? What do you think?

2021-03-10 14:41 UTC, dingo-d commented on tests/Cli/CliInitProjectTest.php
> +	$this->assertEquals('Generates initial setup for WordPress theme project with all files to run a client project, for example: gitignore file for the full WordPress project, continuous integration ex
That's the point of the test. If we change the documentation the test must be changed as well.

Tests shouldn't be set in stone. They are a validation. If you never changed the tests, the architecture of your app would suffer. They should evolve with the app 🙂

2021-03-18 09:43 UTC, IvanGrginovInf approved these changes

2021-03-22 15:33 UTC, dingo-d commented
@infinum/wordpress-team when you have the time feel free to look at the PR. I still have reset, runAll and showAll to test, but since this is a bigger PR (the 7b86f96 commit added lot's of changes when I added a helper). it would be good to check it earlier 🙂

2021-03-23 08:31 UTC, iruzevic requested changes

2021-03-23 08:37 UTC, iruzevic requested changes

2021-03-23 08:37 UTC, iruzevic commented on src/Cli/Cli.php
> -	public function load(string $commandParentName): void
why is this deleted?

2021-03-23 08:37 UTC, iruzevic commented on tests/Blocks/BlockCliTest.php
> -// test('Block CLI command will correctly copy the Block class with defaults', function () {
there are a lot of commented code here

2021-03-23 08:37 UTC, iruzevic commented on tests/Cli/AbstractCliTest.php
> +		// TODO: Implement __invoke() method.
to do

2021-03-23 08:37 UTC, iruzevic commented on tests/Cli/CliTest.php
> +	$this->assertTrue(count($developClasses) === 31, 'Total number of classes is correct');
once we add new featured we should update this number and number on line 86?

2021-03-23 09:21 UTC, dingo-d commented on tests/Cli/CliResetTest.php
> +	$this->assertSame('rm -rf \'/Users/denis.zoljom/Projects/Infinum/Eightshift/eightshift-libs/cliOutput/\'', getenv('SYSTEM_CALLED'));
Oh, my bad! I'll fix this. Totally didn't register my own file path 😅  Good catch! 👍🏼

2021-03-23 09:45 UTC, dingo-d commented on src/Cli/Cli.php
> -	public function load(string $commandParentName): void
This wasn't used anywhere in the lib 🤷🏼‍♂️  What is this used for?

2021-03-23 09:46 UTC, dingo-d commented on tests/Blocks/BlockCliTest.php
> -// test('Block CLI command will correctly copy the Block class with defaults', function () {
That's your commented code 😂  I just wanted to try testing the above test because one of the methods in the CLI part was only used for blocks copying or something like that so I wanted to see if that functionality would break if I change the CLI method 😄

2021-03-23 09:46 UTC, dingo-d commented on tests/Cli/AbstractCliTest.php
> +		// TODO: Implement __invoke() method.
Will remove. PhpStorm adds the stubs automatically. 👍🏼

2021-03-23 09:48 UTC, dingo-d commented on tests/Cli/CliTest.php
> +	$this->assertTrue(count($developClasses) === 31, 'Total number of classes is correct');
Yes. If this test fails you need to update the number. I'll add them as a variable so that it's a bit more clear what they denote.

2021-03-23 09:48 UTC, iruzevic commented on src/Cli/Cli.php
> -	public function load(string $commandParentName): void
Without this nothing is working:

https://github.com/infinum/eightshift-boilerplate/blob/6c49f0a26e053dd3e99e32e53c07fd0dfac39bbf/functions.php#L47

2021-03-23 09:49 UTC, iruzevic commented on tests/Blocks/BlockCliTest.php
> -// test('Block CLI command will correctly copy the Block class with defaults', function () {
😄

2021-03-23 11:27 UTC, dingo-d commented on src/Cli/Cli.php
> -	public function load(string $commandParentName): void
Oh it's used in the boilerplate! 🤦‍♂️

I'll return it and test. 👍

2021-03-23 13:35 UTC, iruzevic approved these changes

2021-03-23 16:25 UTC, dingo-d commented on src/Cli/Cli.php
> -	public function load(string $commandParentName): void
Done

2021-03-23 16:39 UTC, dingo-d commented
Should be all ok now. Waiting from others from the team to take a look 🙂

2021-03-24 08:40 UTC, gabriel-glo approved these changes

2021-03-24 11:24 UTC, merged