Setup tests
infinum/eightshift-libs pull request #161
Opened 2021-03-12 12:03 UTC by goranalkovic-infinum

This took way more than I hoped it would, ran into some weird issues and path brainf##ks, but all is good now 😄 

Changelog:
- `AbstractCli` wasn't detecting the test environment correctly, added the condition that makes it work now
- extracted command name to a const in `SetupCli` and `UpdateCli`
- added check in `UpdateCli` to detect if we're in a test environment and make it point to `setup.json` in `cliOutput` instead of libs root folder
- added tests for `SetupCli` and `UpdateCli`

2021-03-12 14:12 UTC, dingo-d commented on tests/Setup/SetupCliTest.php
> +});
There seem to be some issues with the indentation here.

2021-03-12 14:13 UTC, dingo-d commented on tests/Setup/UpdateCliTest.php
> +});
Indentation

2021-03-12 14:14 UTC, dingo-d commented on tests/Setup/UpdateCliTest.php
> +});
What is being tested here? I think you wanted to test something like

```php
$this->assertFalse($exceptionOccured);
```

Right? If an exception occurred, that variable would be true, and the assertion would be false.

2021-03-12 14:15 UTC, dingo-d requested changes
Left one comment and some indentation issues. Great job 👍🏼

2021-03-12 15:42 UTC, goranalkovic-infinum commented on tests/Setup/UpdateCliTest.php
> +});
I was trying something out and forgot to do the couple of undos to get the try/catch and the assert back. Fixed now 😄

2021-03-12 16:18 UTC, dingo-d approved these changes

2021-03-14 16:29 UTC, iruzevic approved these changes

2021-03-15 07:10 UTC, merged