[WIP] Feature/exception tests
infinum/eightshift-libs pull request #168
Opened 2021-03-24 09:16 UTC by iobrado

Still very much WIP, I've added tests for following classes:
- ComponentException
- InvalidBlock
- InvalidCallback

Also, PR contains few docblock description updates.
In case the approach for the tests is wrong, please provide me with an example how it should be done. Since most tests are quite similar, it shouldn't take too long to fix them.

2021-03-24 09:32 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +<?php
You didn't have to test this one, since it's also covered, but I guess it doesn't hurt to have exceptions covered on their own 😄 

![Screenshot 2021-03-24 at 10 32 00](https://user-images.githubusercontent.com/8638515/112286992-2f314400-8c8c-11eb-9db4-f631d367abe1.png)

2021-03-24 09:35 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +	$this->assertStringContainsString("{$bool} variable is not a string or array but rather boolean", $exceptionBool->getMessage());
When having multiple same assertions in a test, it's a good practice to add the test message at the end, so that, in case something fails, you'll know immediately what failed and why.

For instance, in the first block I'd add something like

```php
	$this->assertIsObject($exceptionObject, "The {$exceptionObject} should be an instance of ComponentException class");
	$this->assertIsObject($exceptionInteger, "The {$exceptionInteger} should be an instance of ComponentException class");
	$this->assertIsObject($exceptionNull, "The {$exceptionNull} should be an instance of ComponentException class");
	$this->assertIsObject($exceptionBool, "The {$exceptionBool} should be an instance of ComponentException class");
```

That way it's easier to identify what failed and where.

2021-03-24 09:37 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +test('Throws exception if ensure_string argument is invalid.', function () {
The name of the test is a bit misleading, as you are not acutally testing the `ensure_string` helper, but rather the `throwNotStringOrArray` method of the exception.

So I'd rename this to something like `Checks if the throwNotStringOrArray method functions correctly.`

2021-03-24 09:38 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +	$this->assertStringContainsString('Object couldn&#039;t be converted to string. Please provide only string or array.', $exceptionObject->getMessage());
```suggestion
	$this->assertStringContainsString('Object couldn\'t be converted to string. Please provide only string or array.', $exceptionObject->getMessage());
```

Just escape the `'` character if you are using it inside a string 😉

2021-03-24 09:40 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +test('Throws exception if unable to locate component.', function () {
Same as the above, the description should be a bit different. Since you are just testing the exceptions themselves.

2021-03-24 09:41 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +	$bool = true;
These could be set inside datasets. Check the [file](https://github.com/infinum/eightshift-libs/blob/release/3.1.0/tests/Datasets/Arguments.php), and [example](https://github.com/infinum/eightshift-libs/blob/release/3.1.0/tests/Helpers/ComponentHelpersTest.php#L39-L44) of their usage.

2021-03-24 09:43 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +	$this->assertStringContainsString("Unable to locate component by path: {$component}", $output->getMessage());
Same comment about adding extra descriptions. Your future self will be glad you added them 😄

2021-03-24 09:44 UTC, dingo-d commented on tests/Exception/ComponentExceptionTest.php
> +beforeAll(function () {
Make sure you add `Monkey\setUp();` before calling the `setupMocks()` and then add

```php
afterAll(function() {
	Monkey\tearDown();
});
```

2021-03-24 09:45 UTC, dingo-d commented on tests/Exception/InvalidBlockTest.php
> +beforeAll(function () {
Same comment about using `beforeAll` and `afterAll` in the test

2021-03-24 09:47 UTC, dingo-d commented on tests/Exception/InvalidBlockTest.php
> +	$this->assertStringContainsString('There are no blocks added in your project.', $missingBlocks->getMessage());
Multiple asserts without comments 🙂

2021-03-24 09:47 UTC, dingo-d commented on tests/Exception/InvalidBlockTest.php
> +	$this->assertStringContainsString("Block in this path {$blockPath} is missing blockName key in its manifest.json.", $missingName->getMessage());
☝🏼

2021-03-24 09:48 UTC, dingo-d commented on tests/Exception/InvalidBlockTest.php
> +	$this->assertStringContainsString('Global Blocks settings manifest.json is missing a key called namespace. This key prefixes all block names.', $missingNamespace->getMessage());
Just add the messages for every test here 😄

2021-03-24 09:49 UTC, dingo-d commented on tests/Exception/InvalidCallbackTest.php
> +test('Create a new instance of the exception for a callback class name that is not recognized.', function () {
Again, the name is a bit odd. You are testing if the `fromCallback` method will return correct response.

2021-03-24 09:49 UTC, dingo-d requested changes
Great job 👍🏼 

I've left some comments on how you can improve the tests a bit.

2021-03-24 09:54 UTC, iobrado commented
Thanks for very detailed and insightful comments 🙂  I'll update the tests according to your suggestions.

2021-03-31 08:00 UTC, iobrado commented
I've added all the other tests and did fixes as you suggested. The only thing I'm still having trouble is in CompoentExceptionTest.php on line 41. I've left that one commented out so maybe you can figure out what's causing that test to fail.

2021-03-31 10:30 UTC, dingo-d approved these changes

2021-03-31 14:06 UTC, dingo-d commented
@iobrado I'm dumb. Can you uncomment that test and add the `&#039;` instead of the `'`. The `esc_html` will escape the special character. 🙈

2021-03-31 14:14 UTC, iobrado commented
> @iobrado I'm dumb. Can you uncomment that test and add the `&#039;` instead of the `'`. The `esc_html` will escape the special character. 🙈

Sure thing, I've updated the code accordingly and pushed the changes 🙂  if everything else is fine, we can merge this.

2021-03-31 14:21 UTC, iruzevic approved these changes

2021-03-31 14:29 UTC, merged