Class media test
infinum/eightshift-libs pull request #169
Opened 2021-03-24 12:49 UTC by kmaric69

2021-03-24 13:03 UTC, dingo-d commented on tests/Media/MediaCliTest.php
> +  $this->assertStringContainsString('after_setup_theme', $generatedMedia);
indent

2021-03-24 13:05 UTC, goranalkovic-infinum commented on tests/Media/MediaExampleTest.php
> +	});
indents

2021-03-24 13:05 UTC, dingo-d commented on tests/Media/MediaExampleTest.php
> +	});
Reindent this please

2021-03-24 13:05 UTC, dingo-d commented on tests/Media/MediaExampleTest.php
> +  $this->assertSame(getenv('TITLE_TAG'), 'true');
Add descriptions for failure like in the above comment to these assertions so that you can differentiate them.

2021-03-24 13:05 UTC, dingo-d requested changes
Left some minor comments

2021-03-25 12:56 UTC, goranalkovic-infinum approved these changes

2021-03-25 13:47 UTC, dingo-d approved these changes

2021-03-25 14:09 UTC, gabriel-glo approved these changes

2021-03-25 15:34 UTC, merged