updating blocks example
infinum/eightshift-libs pull request #172
Opened 2021-03-24 13:43 UTC by iruzevic

2021-03-24 13:46 UTC, goranalkovic-infinum approved these changes

2021-03-24 13:50 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('init', 'EightshiftBoilerplate\Blocks\BlocksExample->registerBlocks()'));
Add an error message in case a test fails so that you can easily differentiate which test failed. For example:

```php
$this->assertSame(10, has_action('init', 'EightshiftBoilerplate\Blocks\BlocksExample->getBlocksDataFullRaw()'), 'The callback getBlocksDataFullRaw should be hooked to init hook with priority 10');
```

Similar should be done with the second one.

Every time you have multiple of the same assertion types (`assertTrue`, `assertStringContainsString`, etc.) it's good to have error message so in case something fails you can find it immediately.

2021-03-24 13:50 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('after_setup_theme', 'EightshiftBoilerplate\Blocks\BlocksExample->changeEditorColorPalette()'));
☝🏼

2021-03-24 13:50 UTC, dingo-d requested changes
Left one comment

2021-03-24 13:52 UTC, iruzevic commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('init', 'EightshiftBoilerplate\Blocks\BlocksExample->registerBlocks()'));
Is it better to maybe a add different tests for each hooks to avoid this issue?

2021-03-24 15:23 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('init', 'EightshiftBoilerplate\Blocks\BlocksExample->registerBlocks()'));
Nah, since you are just testing hooks functionality in the same class. It's always recommended to add the description at the end when using multiple same assertions inside one test.

2021-03-31 23:14 UTC, iruzevic commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('init', 'EightshiftBoilerplate\Blocks\BlocksExample->registerBlocks()'));
fixed

2021-03-31 23:14 UTC, iruzevic commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(11, has_action('after_setup_theme', 'EightshiftBoilerplate\Blocks\BlocksExample->changeEditorColorPalette()'));
fixed

2021-04-01 06:04 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertEquals(false, $blocks);
Can you add an error message, in case this fails

2021-04-01 06:05 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertContains('core/template', $list);
Here as well

2021-04-01 06:05 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertContains('settings', array_keys($items));
☝🏼

2021-04-01 06:05 UTC, dingo-d commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertEmpty($items);
☝🏼

2021-04-01 06:07 UTC, dingo-d requested changes
Left a few comments. The wpfaker is cool, although faker lib has been archived so this is something we'll need to keep in mind when going forward (https://marmelab.com/blog/2020/10/21/sunsetting-faker.html)

2021-04-01 07:46 UTC, iruzevic commented
> Left a few comments. The wpfaker is cool, although faker lib has been archived so this is something we'll need to keep in mind when going forward (https://marmelab.com/blog/2020/10/21/sunsetting-faker.html)

@dingo-d 
Agreed, if there is some other way to mimic WP_Post object let me know and I will remove this dependency.
This i used here and it is not used in the actual implementation. 

<img width="732" alt="Screenshot 2021-04-01 at 09 45 27" src="https://user-images.githubusercontent.com/23283324/113260944-244f6280-92cf-11eb-84b2-ff146684a9ab.png">

2021-04-01 08:52 UTC, gabriel-glo commented on tests/Helpers/ComponentHelpersTest.php
> +	Functions\when('get_template_directory')->justReturn(dirname(__FILE__, 2) . '/data/frontend-libs');
This mock could be extracted to the setup function to avoid repeating.

2021-04-01 09:04 UTC, IvanGrginovInf commented
> > Left a few comments. The wpfaker is cool, although faker lib has been archived so this is something we'll need to keep in mind when going forward (https://marmelab.com/blog/2020/10/21/sunsetting-faker.html)
> 
> @dingo-d
> Agreed, if there is some other way to mimic WP_Post object let me know and I will remove this dependency.
> This i used here and it is not used in the actual implementation.
> 
> <img alt="Screenshot 2021-04-01 at 09 45 27" width="732" src="https://user-images.githubusercontent.com/23283324/113260944-244f6280-92cf-11eb-84b2-ff146684a9ab.png">

@iruzevic I mean you can mock it the same way you mock any other class using `Mockery`. Example can be found in rest routes https://github.com/infinum/eightshift-libs/blob/release/3.1.0/tests/Rest/Routes/RouteExampleTest.php

1. Mock native WP object: `$this->wpRestRequest = \Mockery::mock('alias:WP_REST_Request');`
2. Pass it as argument to any method: $output = `$this->route->routeCallback($this->wpRestRequest);`
3. (Optionally) if you need to mock any WP_Post properties / methods: 

```php 
$this->wpRestRequest
		->shouldReceive('get_body')
		->andReturn(json_encode([$this->mockRequestKey => $this->mockRequestValue]));
```

2021-04-01 09:12 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +	Functions\when('get_template_directory')->justReturn(dirname(__FILE__, 2) . '/data/frontend-libs');
There already is an implementation `Functions\when('get_template_directory')->justReturn(dirname(__FILE__) . '/data');` inside the `setupMocks()` function.

2021-04-01 09:13 UTC, iruzevic commented
> 1. $this->wpPost = \Mockery::mock('WP_Post');

awesome tnx this worked

2021-04-01 10:20 UTC, dingo-d approved these changes
👍🏼  Great job!

2021-04-01 10:44 UTC, gabriel-glo approved these changes

2021-04-01 11:11 UTC, goranalkovic-infinum approved these changes

2021-04-01 11:33 UTC, merged