[WIP] Feature/enqueue tests
infinum/eightshift-libs pull request #177
Opened 2021-04-07 12:20 UTC by iobrado

This PR updates tests for Enqueue class with additional tests for methods from abstract classes. Currently only EnqueueThemeExampleTest.php contains attempts at testing methods from abstract classes.

2021-04-07 12:26 UTC, dingo-d commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +	// Functions\when('wp_localize_script')->justReturn(true);
This should be removed

2021-04-07 12:27 UTC, dingo-d commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +});
This is covered in the example test, no?

2021-04-07 12:29 UTC, dingo-d commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +		putenv("ENQUEUE_STYLE={$args}");
Make sure you do a cleanup of these env variables. You can add `afterEach` and just place `putenv('...=');` there.

2021-04-07 12:33 UTC, iobrado commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +});
It's possible. This was one of the earlier tests I've written so it's possible I didn't even know how to check coverage then 😅

2021-04-07 12:34 UTC, dingo-d commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +	->andReturn('tests/data', '1.0');
Can you indent this?

2021-04-13 21:46 UTC, iruzevic commented
@iobrado is this PR fixed?

2021-04-14 06:58 UTC, iobrado commented
I've updated the EnqueueThemeExampleTest.php according to @dingo-d's instructions. If everything is fine, I'll update other tests accordingly. Hopefully will be done today.

2021-04-14 18:03 UTC, dingo-d commented on tests/Enqueue/Admin/EnqueueAdminExampleTest.php
> +	putenv('...=');
```suggestion
	putenv("REGISTER_STYLE");
	putenv("ENQUEUE_STYLE");
	putenv("REGISTER_SCRIPT");
	putenv("ENQUEUE_SCRIPT");
```

2021-04-14 18:03 UTC, dingo-d commented on tests/Enqueue/Blocks/EnqueueBlockExampleTest.php
> +	putenv('...=');
☝🏼

2021-04-14 18:04 UTC, dingo-d commented on tests/Enqueue/Theme/EnqueueThemeExampleTest.php
> +	putenv('...=');
☝🏼

2021-04-14 18:04 UTC, dingo-d requested changes
Left small comments for cleanup of env vars 🙂

2021-04-15 06:35 UTC, iobrado commented
I've updated the code with better cleanup of env vars, so if everything else is fine, I believe this can be merged. There's only one small issue which causes the coverage for Enqueue classes to be 99.29%.

When registering `EnqueueAdminTest` class for adding some values to `getLocalizations()` protected method, there's no coverage for that method in tests. But when I remove the test class and let it run with `EnqueueAdminExample` class, there is coverage for `getLocalizations()` method, but then `wp_localize_script` in `AbstractEnqueueAdmin.php` isn't covered.

I really have no idea what's causing this, but other than that, everything else is covered just fine.

2021-04-15 11:21 UTC, dingo-d approved these changes
All works now. Great job 👍🏼

2021-04-15 11:22 UTC, iruzevic approved these changes

2021-04-15 11:25 UTC, merged