updating fixes
infinum/eightshift-libs pull request #181
Opened 2021-04-14 09:20 UTC by iruzevic

- adding textdomain correct replace
- fixing some warnings in search/replace
- fixing @package rename

2021-04-14 09:21 UTC, IvanGrginovInf commented on src/Cli/AbstractCli.php
> +	public function camelCaseToKebabCase(string $input): string
Unit test for this one por favor 🙏

2021-04-14 09:23 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +	public function camelCaseToKebabCase(string $input): string
this is not covered fully in the tests so I will add the tests in the next PR.

Setup is failing now so this is a hotfix

2021-04-14 09:23 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +		preg_match_all('!([A-Z][A-Z0-9]*(?=$|[A-Z][a-z0-9])|[A-Za-z][a-z0-9]+)!', $input, $matches);
What's the use of `!` in the regex here exactly?

Seems to me this helper should either be `private` or put in the helpers as a static helper. And tested ofc.

2021-04-14 09:24 UTC, dingo-d requested changes
Left one comment. 

Can you add a test for text-domain replacement as well? So that we verify it works correctly.

2021-04-15 06:36 UTC, IvanGrginovInf approved these changes

2021-04-15 06:37 UTC, IvanGrginovInf commented
@iruzevic approved but phpstan is failing.

2021-04-15 07:25 UTC, iruzevic commented
@IvanGrginovInf fixed phpstan

2021-04-15 07:30 UTC, IvanGrginovInf approved these changes

2021-04-15 10:14 UTC, dingo-d commented on src/Cli/CliHelpers.php
> +		return $output;
```suggestion
		return str_replace('--', '-', $output);
```

2021-04-15 10:16 UTC, dingo-d requested changes
One small comment left

2021-04-15 10:45 UTC, dingo-d approved these changes

2021-04-15 10:49 UTC, merged