Responsive variables
infinum/eightshift-libs pull request #204
Opened 2021-06-08 09:07 UTC by volfkarlo

Changelog:
- added responsive variables handler and its helper functions

PHP part of https://github.com/infinum/eightshift-frontend-libs/pull/362
Works basically the same.

Functions are named the same and function basically the same.

2021-06-08 09:08 UTC, goranalkovic-infinum approved these changes

2021-06-08 09:10 UTC, volfkarlo commented
I apologize for the request, I didn't write tests yet 🙂

2021-06-08 13:57 UTC, dingo-d approved these changes

2021-06-08 15:07 UTC, IvanGrginovInf commented on src/Helpers/Components.php
> +	 * @param array $responsiveAttributes Responsive attributes that are read from component's/block's manifest.
You should write what types of values are supported here otherwise `phpstan` would complain. Try running `composer analyze` in libs.

Something like:

```suggestion
	 * @param array<array<string>> $responsiveAttributes Responsive attributes that are read from component's/block's manifest.
```

If there's too many variations you can also write `array<mixed>` but ideally this should be used as little as possible.

This applies to all other `array` params / returns inside doc-blocks as well.

2021-06-08 15:09 UTC, volfkarlo commented on src/Helpers/Components.php
> +	 * @param array $responsiveAttributes Responsive attributes that are read from component's/block's manifest.
Quite useful info. I'll definitely check it out and make changes.
Thx! 😄

2021-06-09 06:38 UTC, volfkarlo commented on src/Helpers/Components.php
> +	 * @param array $responsiveAttributes Responsive attributes that are read from component's/block's manifest.
What I could notice in our libs is that something like `array<...>` occurs 10 times and `@param array` around 100ish times and `@return array` 170 times. I believe the reason behind it is that the structure is waaay more complex than one layer(`array<array<array<array<mixed>>>>`). I would agree that this would be the reason more to do so, but I think that it might be ok not to "crowd" code with it because it's really complex and, what I believe, not a lot of people would read it since you anyway get lost in all of this nesting.

Also sometimes, this kind of type determination is not even possible since our manifest contains different nesting depths. For example, `componentName` is one level deep, and variables field is 4-5 levels deep which again brings so many possibilities and options that, in my opinion, documenting it doesn't bring that much.

> Still, it would be good to add those if possible or if you have/expect consistent types inside array values.
Is it ok if I just leave it like this for now? I found one spot where I could put it and it would be of a type `array<mixed>` which is not that useful.

2021-06-09 07:26 UTC, gabriel-glo commented on tests/data/src/Blocks/components/responsiveVariables/manifest.json
> +{
Can this really be classified as a component. To me this would work better as a standalone JSON file in Blocks directory (alongside the main manifest.json file)

2021-06-09 07:48 UTC, iruzevic requested changes

2021-06-09 07:48 UTC, iruzevic commented on tests/data/src/Blocks/components/responsiveVariables/manifest.json
> +{
this works only on blocks and components so we should follow that folder convention so for me this looks ok

2021-06-09 07:48 UTC, iruzevic commented on tests/data/src/Blocks/components/responsiveVariables/manifest.json
> +    "variableValueDesktop": {
please fix indentations in this file

2021-06-09 08:23 UTC, iruzevic approved these changes

2021-06-09 08:37 UTC, merged