Props helper fix
infinum/eightshift-libs pull request #206
Opened 2021-06-18 10:48 UTC by goranalkovic-infinum

Solves a major bug with output order.

If your component had
```
...
componentWhichIsAliasToParagraph
paragraph
...
```
in the dependency list, and you called
```php
Blocks::props($attributes, 'paragraph', 'componentWhichIsAliasToParagraph')
```
, the attributes you want (here belonging to `componentWhichIsAliasToParagraph`) would get overwritten in the next loop (here with the default `paragraph` options) and the output would be wrong.

This PR makes it so you first collect all the attributes from dependencies and then at the end it goes through the component that you want (here `componentWhichIsAliasToParagraph`).

2021-06-18 10:54 UTC, volfkarlo reviewed
Left few comments. Mostly to explain functions/variables a bit more in detail.

2021-06-18 10:54 UTC, volfkarlo commented on src/Helpers/Components.php
> +		// Loop all attributes but the actual (newNameInternal) component.
Maybe a tiny bit bigger clarification would be awesome.
More to explain what is it for than what it doing.. For example.

"Searching for the newNameInternal component" or "Extracting something from something else"

2021-06-18 10:54 UTC, volfkarlo commented on src/Helpers/Components.php
> +		foreach ($attributes as $key => $value) {
It would be awesome if you would be able to name it somehow other than key and value(preName => postName or something)

2021-06-18 10:54 UTC, volfkarlo commented on src/Helpers/Components.php
> +		foreach ($attributes as $key => $value) {
Same as above.

2021-06-18 11:52 UTC, dingo-d commented on src/Helpers/Components.php
> +		if (empty($newName)) {
The above will work. The `$newName` must be a `string`, and it defaults to an empty string `''`, which is a falsy value so `!$newName` will give the same result as `empty($newName)`, without the overhead of calling a function 🙂

2021-06-18 11:53 UTC, dingo-d requested changes
One comment left.

2021-06-18 13:48 UTC, dingo-d approved these changes

2021-06-23 07:45 UTC, iruzevic reviewed
Is this there the same issue with the frontend libs or this is only here?

2021-07-05 06:48 UTC, volfkarlo approved these changes
Maybe not the clearest version of comments. But I can't suggest any better 😄 
Well done Goc!

2021-07-05 08:27 UTC, gabriel-glo approved these changes

2021-07-05 08:36 UTC, IvanGrginovInf approved these changes

2021-07-05 09:26 UTC, goranalkovic-infinum commented
@iruzevic this probably isn't relevant anymore as the whole props helper was rewritten, right?

2021-07-05 14:00 UTC, IvanGrginovInf commented
> @iruzevic @volfkarlo @IvanGrginovInf this probably isn't relevant anymore as the whole props helper was rewritten, right?

Yup, the props helper is now completely different.

2021-07-05 14:08 UTC, goranalkovic-infinum commented
Closing as solution is not relevant anymore due to current props helper changes.

2021-07-05 14:08 UTC, closed without merging