Fix tests
infinum/eightshift-libs pull request #212
Opened 2021-07-05 16:02 UTC by IvanGrginovInf

Fixes broken tests as part of https://github.com/infinum/eightshift-libs/pull/211

Changelog
---
- `checkAttr` tests
- `props` tests (done less detailed than the ones in JS since that was a bit of on overkill + the props helper is much more simplified now)
- Removed tests which test native PHP functionality (and cause IntelliSense errors in editor)
- Fixed some IntelliSense errors / typos

2021-07-05 16:05 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +	$this->assertEquals('right', $results, "The set attribute should be {$attributes['prefixedMultipleTimesButtonAlign']}");
```suggestion
	$this->assertSame('right', $results, "The set attribute should be {$attributes['prefixedMultipleTimesButtonAlign']}");
```

Always use strict check (type and value). `assertEquals` will just check the value.

2021-07-05 16:06 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +	$this->assertEquals('heading', $output['prefix']);
```suggestion
	$this->assertSame('heading', $output['prefix']);
```

2021-07-05 16:06 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +	$this->assertEquals('headingTypography', $output['prefix']);
```suggestion
	$this->assertSame('headingTypography', $output['prefix']);
```

2021-07-05 16:07 UTC, IvanGrginovInf commented on tests/Helpers/ComponentHelpersTest.php
> +	$this->assertEquals('right', $results, "The set attribute should be {$attributes['prefixedMultipleTimesButtonAlign']}");
Got `109` results for `assertEquals` in our tests. 😄  but will change it.

2021-07-05 16:07 UTC, dingo-d requested changes
Left some minor comments 👍🏼

2021-07-05 16:08 UTC, dingo-d commented on tests/Helpers/ComponentHelpersTest.php
> +	$this->assertEquals('right', $results, "The set attribute should be {$attributes['prefixedMultipleTimesButtonAlign']}");
😱

2021-07-05 16:09 UTC, IvanGrginovInf commented
> Left some minor comments 👍🏼

Replaced all instances of `assertEquals` with `assertSame`, all tests still pass. 🎉

2021-07-05 16:11 UTC, IvanGrginovInf commented
@iruzevic please check the changes in `src/Helpers/Components.php`. This was causing tests to fail (`$attributeValue` being set to array as a fallback in `setVariablesToBreakpoints()` but then that value was used in a `str_replace()` in `variablesInner()`) but I'm not sure if the change properly fixes the issue. The tests pass with that change tho.

2021-07-05 16:14 UTC, dingo-d approved these changes

2021-07-05 16:14 UTC, dingo-d commented
Tip to other reviewers: go commit by commit 🙂 Last one is just changing `assertEquals` to `assertSame` 🙂

2021-07-06 07:07 UTC, goranalkovic-infinum approved these changes

2021-07-06 08:32 UTC, closed without merging