Add a filter for rendering block data
infinum/eightshift-libs pull request #236
Opened 2021-09-24 15:28 UTC by dingo-d

Used if we have a default paragraph block in the editor.

2021-09-24 15:29 UTC, mbmjertan approved these changes

2021-09-24 15:30 UTC, goranalkovic-infinum submitted a review, later dismissed

2021-09-24 20:06 UTC, goranalkovic-infinum approved these changes

2021-09-24 20:07 UTC, goranalkovic-infinum requested changes
Please check why the unit test is failing

2021-09-24 20:37 UTC, iruzevic approved these changes

2021-11-02 05:15 UTC, dingo-d commented
The codecov fails, but I've fixed the tests and phpcs issues.

@iruzevic @goranalkovic-infinum

2021-11-02 07:07 UTC, iruzevic approved these changes
bravo

2021-11-02 08:13 UTC, goranalkovic-infinum approved these changes

2021-11-02 09:38 UTC, merged