Transform first letter new key to uppercase
infinum/eightshift-libs pull request #238
Opened 2021-10-04 15:04 UTC by iobrado

Proposed fix related to issue #237. More detailed description is in mentioned issue.

2021-10-04 15:14 UTC, simun-ivanac approved these changes

2021-10-05 09:05 UTC, iruzevic approved these changes

2021-10-05 09:11 UTC, dingo-d requested changes
Good job. You'll need to see why the CI/CD checks are failing and fix them. Also, make sure you write a test for this addition 🙂

2021-10-08 06:51 UTC, volfkarlo submitted a review, later dismissed

2021-11-03 11:26 UTC, dingo-d commented
I've fixed the failing tests so when you find the time just rebase your branch and it should be ok. After you write tests, because otherwise you'll get a failure in coverage bot 😄

2021-11-03 19:27 UTC, dingo-d approved these changes

2021-11-03 19:28 UTC, iruzevic approved these changes

2021-11-04 07:35 UTC, merged