Gutenberg internationalization
infinum/eightshift-libs pull request #250
Opened 2021-12-09 16:38 UTC by mbmjertan

# Description

Adds a method to `I18nExample.php` which hooks to `enqueue_block_editor_assets` to allow blocks in the editor to be internationalized.

Translations should be exported as JED files and have the name in this format: `{textdomain}-{locale}-{handle}.json` into path defined by the method (`src/I18n/languages` in this example). 

This export can be done automatically with Glotpress, and there are tools in WP-CLI to help with that (but they seemed to produce more than one file when I tried using them, so I'm not really sure they're behaving properly. maybe I'm just being dumb :shrug:)

Also adds a `getProjectPath` helper to `ConfigExample.php`, as it's referenced in other example classes, but missing from the `ConfigExample.php`

# Screenshots / Videos
![Screenshot 2021-12-09 at 17 34 15](https://user-images.githubusercontent.com/1742806/145437279-83124525-5829-4b03-960a-8facb257c6bc.png)

# Linked documentation PR

2021-12-10 11:16 UTC, dadadavorin submitted a review, later dismissed

2021-12-12 16:59 UTC, dingo-d commented on src/I18n/I18nExample.php
> +
```suggestion
```

2021-12-12 16:59 UTC, dingo-d commented on src/I18n/I18nExample.php
> +	 * defined below.
```suggestion
	 * Load the theme text domain for JavaScript translations
	 *
	 * You should export your locales as a JED file named
	 * {textdomain}-{locale}-{handle}.json into the project path
	 * defined below.
```

2021-12-12 17:00 UTC, dingo-d requested changes
Left few small comments, looks good otherwise 🙂

2021-12-13 09:19 UTC, dingo-d commented
Not sure what happened with phpcs, but can you just fix those?

2021-12-13 09:22 UTC, iruzevic submitted a review, later dismissed

2021-12-13 16:46 UTC, mbmjertan commented
Thanks for the heads up, @dingo-d. I've fixed the introduced issues `composer standards:fix`.

2021-12-13 16:50 UTC, iruzevic approved these changes

2021-12-13 16:59 UTC, dingo-d approved these changes

2021-12-14 08:32 UTC, goranalkovic-infinum approved these changes

2021-12-14 08:34 UTC, merged

2021-12-14 08:57 UTC, volfkarlo approved these changes
One dot, but If PHPCS is not complaining why should I? 🙂

2021-12-14 08:57 UTC, volfkarlo commented on src/I18n/I18nExample.php
> +	 * Load the theme text domain for JavaScript translations
```suggestion
	 * Load the theme text domain for JavaScript translations.
```