Feature/gdpr settings
infinum/eightshift-libs pull request #252
Opened 2021-12-17 13:36 UTC by iobrado

# Description

- adds an example class for Analytics and GDPR Settings which are generated as an ACF Options Page.
- adds a WP CLI command for creating a Analytics and GDPR Settings class in project.

### To-do:
- [x] write tests

# Screenshots / Videos

https://user-images.githubusercontent.com/23059501/165910496-5432c6c1-626a-4cea-a3ff-77cc6ed61fe1.mov

2021-12-20 07:33 UTC, iruzevic reviewed
looks good

2021-12-20 08:05 UTC, dingo-d requested changes
@volfkarlo Is this ok with the rework you did on Infinum's web because I remember you saying that you've changed the GDPR component quite a bit.

@iobrado can you check why the unit tests are failing, and fix them? Thanks!

2021-12-20 08:23 UTC, iobrado commented
> @iobrado can you check why the unit tests are failing, and fix them? Thanks!

Sure thing, when I start writing tests for my additions, I'll also check in more detail what's causing the tests to fail.

2021-12-22 07:17 UTC, iobrado commented
I've fixed the issue with failing tests and written tests. Still quite low coverage on one so I'll have to check what's that about. Once it's fixed, I'll mark it as ready for review.

2021-12-22 09:02 UTC, dingo-d submitted a review, later dismissed

2022-01-14 14:04 UTC, mbmjertan commented on tests/GdprSettings/GdprSettingsCliTest.php
> +	$this->assertStringNotContainsString('someRandomMethod', $generatedMeta);
Would it be possible to use Reflection to check whether the methods are present (and have a given stub)?

2022-01-17 09:48 UTC, dingo-d commented on tests/GdprSettings/GdprSettingsCliTest.php
> +	$this->assertStringNotContainsString('someRandomMethod', $generatedMeta);
What's the benefit of using reflection in this case? We just need to check if some strings appear in a file 🤷🏼‍♂️

2022-01-21 07:35 UTC, iobrado commented on src/GdprSettings/GdprSettingsExample.php
> +								'instructions' => esc_html__('Use {%manage_link|Link text%} placeholder to correctly link the manage cookie link on the frontend.', 'eightshift-libs'), // phpcs:ignore Generic.Files.LineLengt
Yeah, it is kinda rough explanation 😅

Basically, when you have "You can manage cookies on {%manage_link|this link%}" in editor, on frontend you will get the message "You can manage cookies on [this link](#)".

When you click on the link, it opens the advanced GDPR modal. If there is a better way of wording these instructions, I'll gladly change it 🙂

2022-01-24 16:13 UTC, gabriel-glo approved these changes

2022-04-22 15:36 UTC, mbmjertan submitted a review, later dismissed

2022-04-24 07:53 UTC, dingo-d approved these changes
@volfkarlo Can you see what needs to be added (if something has to be added) as you have the most recent experience with this?

2022-04-25 07:24 UTC, iobrado commented
@dingo-d Sure, I will rebase and fix the conflicts. I did talk to Karlo and quite a bit has changed, so it will require some refactoring.

2022-04-25 10:32 UTC, volfkarlo commented
@iobrado and I talked about it. It should be all good after refactor 😄

2022-04-28 10:18 UTC, iobrado commented
I refactored this, but still have to update the tests

2022-04-29 08:33 UTC, iobrado commented
I've added the tests, fixed the issues that were causing the checks to fail and added a new video to PR description.

2022-05-01 09:55 UTC, dingo-d commented on tests/AnalyticsGdpr/AnalyticsGdprCliTest.php
> +	$generatedMeta = file_get_contents(dirname(__FILE__, 3) . '/cliOutput/src/AnalyticsGdpr/AnalyticsGdpr.php');
Can you change all the assertions to [expectations API](https://pestphp.com/docs/expectations)?

2022-05-03 11:46 UTC, iobrado commented on tests/AnalyticsGdpr/AnalyticsGdprCliTest.php
> +	$generatedMeta = file_get_contents(dirname(__FILE__, 3) . '/cliOutput/src/AnalyticsGdpr/AnalyticsGdpr.php');
I updated the tests. Is this according to your... expectations? 🤣

2022-05-03 12:49 UTC, gabriel-glo approved these changes

2022-05-04 08:43 UTC, dingo-d commented on tests/AnalyticsGdpr/AnalyticsGdprCliTest.php
> +	expect($generatedMeta)->toBeString()->not->toContain('someRandomMethod');
```suggestion
    expect($generatedMeta)
        ->toBeString()
        ->toContain('class AnalyticsGdpr implements ServiceInterface')
        ->toContain('acf_add_options_page')
        ->toContain('acf_add_local_field_group')
        ->toContain('createAnalyticsPage')
        ->toContain('registerAnalytics')
        ->toContain('createGdprModalPage')
        ->toContain('registerGdprModalSettings')
        ->toContain('prepareGdprModalData')
        ->not->toContain('someRandomMethod');
```

Expectations are great because you can chain them 🙂

2022-05-04 08:46 UTC, dingo-d commented on tests/AnalyticsGdpr/AnalyticsGdprCliTest.php
> +	expect($documentation[$descKey])->toBeString()->toBe('Generates project Analytics and GDPR Settings classes using ACF.');
```suggestion
	expect($documentation)
		->toBeArray()
		->toHaveKey($descKey);
	
	expect($documentation[$descKey])
		->toBeString()
		->toBe('Generates project Analytics and GDPR Settings classes using ACF.');
```

I like to put multiple chained expectations one after another, makes it a bit more readable 🙂

2022-05-04 08:48 UTC, dingo-d commented on tests/AnalyticsGdpr/AnalyticsGdprExampleTest.php
> +	expect(\function_exists('esc_html__'))->toBeTrue();
You don't need to check WP's implementation, there are enough of tests covering that in the WP Core testing suite 😄

2022-05-04 08:49 UTC, dingo-d commented on tests/ThemeOptions/ThemeOptionsCliTest.php
> +	expect($generatedMeta)->toBeString()->not->toContain('someRandomMethod');
```suggestion
    expect($generatedMeta)
        ->toBeString()
        ->toContain('class ThemeOptions implements ServiceInterface')
        ->toContain('acf_add_options_page')
        ->toContain('acf_add_local_field_group')
        ->toContain('createThemeOptionsPage')
        ->toContain('registerThemeOptions')
        ->not->toContain('someRandomMethod');
```

2022-05-04 08:49 UTC, dingo-d commented on tests/ThemeOptions/ThemeOptionsCliTest.php
> +	expect($documentation[$descKey])->toBeString()->toBe('Generates project Theme Options class using ACF.');
```suggestion
    expect($documentation)
        ->toBeArray()
        ->toHaveKey($descKey);

    expect($documentation[$descKey])
        ->toBeString()
        ->toBe('Generates project Theme Options class using ACF.');
```

2022-05-04 08:50 UTC, dingo-d requested changes
It almost met my expectations 😂 Left you some additional comments, mostly about readability and chaining.

2022-05-04 10:18 UTC, dingo-d approved these changes

2022-06-01 07:19 UTC, volfkarlo requested changes
Minor comments. Great job 👏 😄

2022-06-01 07:19 UTC, volfkarlo commented on src/AnalyticsGdpr/AnalyticsGdprExample.php
> +	 * Analytics api page slug
```suggestion
	 * Analytics api page slug.
```

2022-06-01 07:19 UTC, volfkarlo commented on src/AnalyticsGdpr/AnalyticsGdprExample.php
> +	 * The title of the functional cookies.
```suggestion
	 * The title of the performance cookies.
```

2022-06-01 07:19 UTC, volfkarlo commented on src/AnalyticsGdpr/AnalyticsGdprExample.php
> +	 * The summary of the functional cookies.
```suggestion
	 * The summary of the performance cookies.
```

2022-06-03 06:13 UTC, iobrado commented
I've updated the tests in `BlocksExampleTest.php` to use Expectations API, but maybe it would be better for someone else to check the errors in these tests and fix them.

2022-06-06 08:28 UTC, dingo-d requested changes
@iobrado can you just check why some tests are failing, and the issue with PHPStan.

I could swear we fixed this PHPStan issue 🤔

2022-06-06 17:41 UTC, dadadavorin approved these changes

2022-06-07 06:24 UTC, volfkarlo approved these changes
Seems all good! 😄 👏

2022-06-07 06:24 UTC, merged