Add Cli command to create custom cli commands
infinum/eightshift-libs pull request #253
Opened 2021-12-22 09:30 UTC by Lukicdev

# Description

Add WP CLI command to generate custom CLI command to project 

# Screenshots / Videos

https://user-images.githubusercontent.com/47175420/147069665-60bc12e9-faf9-4835-9cfc-033472464699.mp4

2021-12-22 09:48 UTC, dingo-d commented
![lol](https://user-images.githubusercontent.com/8638515/147072390-40865c20-d849-4451-8c4c-f32431765da6.jpg)

I just couldn't pass the opportunity 😂 

Can you just check why the phpstan is failing and why the codecov marked this as a failure?

2021-12-22 11:02 UTC, dingo-d commented on src/CliCommands/AbstractCustomCommand.php
> +abstract class AbstractCustomCommand implements ServiceInterface
Why is this class needed? There already is an `AbstractCli` class that handles command registration? Is there anything different that this abstract class does from AbstracCli one? 

If yes, can't this different part be included in an AbstractCli class?

2021-12-22 11:06 UTC, dingo-d requested changes
Left one question, good job otherwise 👍🏼

2022-01-20 13:00 UTC, dingo-d approved these changes
Great job!

2022-01-20 13:15 UTC, goranalkovic-infinum approved these changes

2022-01-21 10:03 UTC, merged