updating change log for new release
infinum/eightshift-libs pull request #257
Opened 2022-02-02 08:03 UTC by iruzevic

# Description

- updating changelog

2022-02-02 08:05 UTC, iobrado approved these changes
Found just one typo 🙂

2022-02-02 08:05 UTC, iobrado commented on CHANGELOG.md
> +- Option ot override default block class prefix in the blocks global settings manifest.
```suggestion
- Option to override default block class prefix in the blocks global settings manifest.
```

2022-02-02 08:06 UTC, iobrado approved these changes

2022-02-02 08:11 UTC, dadadavorin approved these changes
Looks good. Just few spelling suggestions

2022-02-02 08:11 UTC, dadadavorin commented on CHANGELOG.md
> +- DI container caching on production, or staging.
```suggestion
- DI container caching on production or staging.
```

2022-02-02 08:11 UTC, dadadavorin commented on CHANGELOG.md
> +- Limit enqueue admin only to admin area and not block editor.
```suggestion
- Limit enqueue admin only to admin area but not to the block editor.
```

2022-02-02 08:14 UTC, dadadavorin approved these changes

2022-02-02 08:19 UTC, iobrado submitted a review, later dismissed

2022-02-02 08:20 UTC, simun-ivanac submitted a review, later dismissed

2022-02-02 08:26 UTC, mbmjertan requested changes

2022-02-02 08:26 UTC, mbmjertan commented on CHANGELOG.md
> +- Changed directory separator from `\` to `DIRECTORY_SEPARATOR` constant to be able to work cross-platform.
Previous separator is wrongly listed here, see PR #234
```suggestion
- Changed directory separator from `/` to `DIRECTORY_SEPARATOR` constant to be able to work cross-platform.
```

2022-02-02 08:27 UTC, mbmjertan submitted a review, later dismissed

2022-02-02 08:29 UTC, goranalkovic-infinum approved these changes

2022-02-02 08:46 UTC, simun-ivanac submitted a review, later dismissed

2022-02-02 09:46 UTC, gabriel-glo approved these changes

2022-02-02 10:23 UTC, dingo-d commented on CHANGELOG.md
> +
Can you add the missing releases? I've added them here, so just copy them from here: https://github.com/infinum/eightshift-libs/blob/3.1.0/CHANGELOG.md (just make sure to link them, I just saw that I didn't link them 🙈)

2022-02-02 10:24 UTC, dingo-d commented on CHANGELOG.md
> +- New prop to outputCssVariables called $customSelector.
```suggestion
- New attribute to `outputCssVariables` called `$customSelector`.
```

2022-02-02 10:25 UTC, dingo-d commented on CHANGELOG.md
> +- Limit enqueue admin only to admin area but not to the block editor.
This should go under `Changed` section of the changelog

2022-02-02 10:25 UTC, dingo-d commented on CHANGELOG.md
> +- More tests.
I don't think we need to mention we added more tests, that should be a given 😄

2022-02-02 10:26 UTC, iruzevic commented on CHANGELOG.md
> +- More tests.
We sound smart :D

2022-02-02 10:33 UTC, dingo-d requested changes
Left some minor comments, otherwise looks good to me. I pulled the develop branch locally for one project and I didn't see any breakage on a clients site, so I think we can tag this as 4.1.0 🙂

2022-02-03 07:12 UTC, iruzevic commented on CHANGELOG.md
> +
Done

2022-02-03 07:13 UTC, iruzevic commented on CHANGELOG.md
> +- Limit enqueue admin only to admin area but not to the block editor.
done

2022-02-03 07:13 UTC, iruzevic commented on CHANGELOG.md
> +- More tests.
removed

2022-02-03 07:14 UTC, merged