Feature/inline style
infinum/eightshift-libs pull request #263
Opened 2022-03-07 14:25 UTC by iruzevic

# Description

- Added everything to a global variable $esBlocks just like in JS window object
- refactored output css variable to one style tag
- refactoring getManifest to determine the component/block from path
- changing some function to private
- optimized loading of block for only one read for manifest.json

# Screenshots / Vide
![Screenshot 2022-03-07 at 15 15 23](https://user-images.githubusercontent.com/23283324/157052083-afcdf640-1081-4b70-a575-ee7e4ee4fa25.png)
![Screenshot 2022-03-07 at 15 15 52](https://user-images.githubusercontent.com/23283324/157052099-5f3e5fa0-6185-4c90-893d-34ed2ec86024.png)
os

<img width="453" alt="Screenshot 2022-03-07 at 15 22 34" src="https://user-images.githubusercontent.com/23283324/157052133-9eb49bd7-f6da-4a41-ae53-6f0d1eb85c40.png">

2022-03-07 15:34 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
>  		}
I'd move this above the line where you save the namespace to an internal variable.

2022-03-07 15:34 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +			function ($block) use ($namespace) {
```suggestion
			static function ($block) use ($namespace) {
```

2022-03-07 15:38 UTC, dingo-d commented on src/Helpers/Components.php
> +			}
The `$items` should be placed after the `!isset` check.

2022-03-07 15:41 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +			Components::getSettings('blocks', '', $this->namespace) ?? []
The return type of `getSettings` is mixed, so it can be `null`?

Because if it cannot be null, the null coalesce operator will never default to `[]`...

2022-03-07 15:50 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +		$separator = DIRECTORY_SEPARATOR;
I see this used a lot, can we extract this to a private member variable? Class constants won't help, because they cannot be referenced during interpolation.

2022-03-07 15:56 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
>  				$block = implode(' ', (array)file(($blockPath)));
In the case the `$blockPath` is false, the `$block` will be an empty string. The `parseManifest` handles this correctly?

The same is for the 697 line

2022-03-07 16:03 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +					throw InvalidBlock::missingComponentNameException($componentPath);
Tbh, not sure what will happen if you throw an error inside array_map 🙈 We should cover this with tests

https://3v4l.org/P8CQK

2022-03-07 16:17 UTC, dingo-d requested changes
Left some comments, tests will need to be updated.

2022-03-07 17:18 UTC, iruzevic commented on src/Blocks/AbstractBlocks.php
>  				$block = implode(' ', (array)file(($blockPath)));
this is old code and it should be covered with test so I think it is ok

2022-03-07 17:18 UTC, iruzevic commented on src/Blocks/AbstractBlocks.php
> +					throw InvalidBlock::missingComponentNameException($componentPath);
agreed

2022-03-07 17:20 UTC, iruzevic commented on src/Helpers/Components.php
> +	public static function getManifest(string $path, $useGlobal = true): array
I have updated this a bit. getSettings can only return string/array. So it should be ok. I will cover this with test later on

2022-03-07 20:19 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +			Components::getSettings('blocks', '', $this->namespace) ?? []
Yeah, if it'll never return null, then you can also remove the `?? []` part.

https://3v4l.org/Zp8Hp

2022-03-08 07:50 UTC, dingo-d commented on src/Blocks/AbstractBlocks.php
> +	 * Directory separator used for cross compatibility.
```suggestion
	 * Directory separator used for OS cross-compatibility.
```

2022-03-08 19:50 UTC, volfkarlo reviewed
Just a few questions left 😄 
Awesome job! 😄

2022-03-08 19:50 UTC, volfkarlo commented on tests/Blocks/BlocksExampleTest.php
> +	$this->assertSame(getenv('BLOCK_TYPE'), 'true', 'Calling void method register_block_type caused no side affects');
```suggestion
	$this->assertSame(getenv('BLOCK_TYPE'), 'true', 'Calling void method register_block_type caused no side effects');
```
I think, not sure.

2022-03-08 19:50 UTC, volfkarlo commented on src/Helpers/Components.php
> +	private static function getDefaultBreakpoints(array $breakpoints): array
Are these breakpoints presorted when entering the function? If they are coming straight from the manifest, I would suggest ensuring it by sorting it by the value of the breakpoint.

2022-03-09 09:54 UTC, mbmjertan reviewed
This is great!

I've left two comments regarding code style. 

I'll take a closer look at the logic later, as this seems like magic at the moment and it's very difficult to read through the diffs due to the amount of changes, so I'll have to clone it to read through. 👀

2022-03-09 09:54 UTC, mbmjertan commented on src/Helpers/Components.php
>  	/**
Regarding code style here: As this is mostly used to support string interpolation, e.g. in `$sep = self::$sep`and afterwards `$componentPath = "{$parentPath}{$sep}$component"`, I'm not too sure that this should be a class property.

I'd prefer:
1. using `$sep = DIRECTORY_SEPARATOR;` in methods themselves, as we're instantiating method-scope variables either way
2. `$sep` being a class constant (not a property, and not a static property), but at that point we're just adding a class constant that's equal to a global constant

2022-03-09 09:54 UTC, mbmjertan commented on src/Helpers/Components.php
> +					if ($item['name'] === $breakpoint && $item['type'] === $type && (!empty((string) $attributeValue) || gettype($attributeValue) === 'integer' || gettype($attributeValue) === 'float' || gettype($at
Maybe break these compound conditionals into newlines for readability, e.g. something like this, but with better formatting
```suggestion
					if ($item['name'] === $breakpoint 
					&& $item['type'] === $type 
					&& (!empty((string) $attributeValue) 
						|| gettype($attributeValue) === 'integer' 
						|| gettype($attributeValue) === 'float' 
						|| gettype($attributeValue) === 'double' 
						|| $attributeValue === '0')
					) { 
```

2022-03-09 09:57 UTC, mbmjertan commented on src/Blocks/AbstractBlocks.php
> +					throw InvalidBlock::missingComponentNameException($componentPath);
This should have test coverage, yeah, but not sure what you meant by this, @dingo-d:

>  not sure what will happen if you throw an error inside array_map
 
What _could_ happen apart from the usual exception handling logic (that an exception has to be caught somewhere up the call stack or it results in a Fatal Error)? This is a genuine question, I have no idea what could be a problem here.

2022-03-18 08:46 UTC, iobrado requested changes
Left just one question. As soon as that's resolved, I'll approve 🙂

2022-03-18 08:46 UTC, iobrado commented on src/Cli/AbstractCli.php
> +					mkdir($destinationPath, 0777, true);
Is there a specific reason this is set to `0777`?  Folders usually have permissions set to `0755`

2022-03-18 08:57 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +					mkdir($destinationPath, 0777, true);
I think by default the PHP sets it to 0777, we can change that to 0755, I think that's the default value that bash sets. Good catch 👍🏼

2022-03-18 08:59 UTC, iobrado commented on src/Cli/AbstractCli.php
> +					mkdir($destinationPath, 0777, true);
We should definitely test how it behaves if set to 0755, just to be sure it doesn't break anything. Generally, having 0777 is a potential security risk since everyone has read, write and execute permissions.

2022-03-18 09:00 UTC, goranalkovic-infinum requested changes
Left one suggestion and 2 missing thing comments 😄 

Awesome job!

2022-03-18 09:03 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +					mkdir($destinationPath, 0777, true);
fixed

2022-03-18 09:06 UTC, iobrado approved these changes

2022-03-18 09:07 UTC, goranalkovic-infinum approved these changes

2022-03-18 09:08 UTC, simun-ivanac approved these changes

2022-03-18 09:57 UTC, mbmjertan approved these changes

2022-03-18 10:08 UTC, merged

2022-03-18 10:15 UTC, volfkarlo reviewed
Just suggestions for the next merge 😄

2022-03-18 10:15 UTC, volfkarlo commented on tests/data/src/Blocks/components/button-false/manifest.json
> +{
Spaces instead of tabs in this whole file 😄

2022-03-18 10:15 UTC, volfkarlo commented on tests/Blocks/BlocksExampleTest.php
> +use EightshiftLibs\Helpers\Components;
Extra new line above this one

2022-03-18 10:15 UTC, volfkarlo commented on tests/Blocks/BlockVariationCliTest.php
> +
extra new line above this one

2022-03-18 10:15 UTC, volfkarlo commented on tests/Blocks/BlockComponentCliTest.php
> +
extra new line above this one

2022-03-18 10:15 UTC, volfkarlo commented on tests/Blocks/BlockCliTest.php
> +
extra new line above this one

2022-03-18 10:15 UTC, volfkarlo commented on src/Setup/UpdateCli.php
> +
extra new line.