Feature/cli
infinum/eightshift-libs pull request #276
Opened 2022-04-13 16:03 UTC by iruzevic

# Description

- corrections to WP cli init method to use new service interface
- fixes to command to create custom WP cli command

2022-04-14 06:55 UTC, dingo-d commented on tests/WpCli/WpCliExampleTest.php
> +// };
Remove commented code

2022-04-14 06:55 UTC, dingo-d commented on tests/WpCli/WpCliTest.php
> +	$this->assertStringContainsString('class TestWpCli implements ServiceCliInterface', $customCommand);
Expectations API 🙏🏼

2022-04-14 06:56 UTC, dingo-d requested changes
Left some minor comments. Otherwise looks good to me 👍🏼 

Can you just see about the service instantiation - test that part with automated tests?

2022-04-14 07:57 UTC, dadadavorin approved these changes

2022-04-15 07:06 UTC, volfkarlo approved these changes
👏

2022-04-15 10:41 UTC, iruzevic commented on tests/WpCli/WpCliTest.php
> +	$this->assertStringContainsString('class TestWpCli implements ServiceCliInterface', $customCommand);
👍

2022-04-17 11:58 UTC, merged