Feature/label generator
infinum/eightshift-libs pull request #277
Opened 2022-04-13 17:00 UTC by iruzevic

# Description

- moving label generator to trait
- fixing post type
- adding LG to taxonomy
- fixing test

2022-04-14 06:36 UTC, dingo-d commented on src/Helpers/LabelGeneratorTrait.php
> +		$requiredCouns = [
```suggestion
		$requiredNouns = [
```

2022-04-14 06:36 UTC, dingo-d commented on src/Helpers/LabelGeneratorTrait.php
> +		if (\count($nouns) !== \count($requiredCouns)) {
```suggestion
		if (\count($nouns) !== \count($requiredNouns)) {
```

2022-04-14 06:41 UTC, dingo-d commented on src/Helpers/LabelGeneratorTrait.php
> +					$nouns[3]
Since these are no longer keyed, you can use `...$nouns` instead (especially since we are not supporting anything less than PHP 7.4).

2022-04-14 06:44 UTC, dingo-d commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('post', $generatedCPT);
```suggestion
	expect(generatedCPT)
		->toContain('class LocationTaxonomy extends AbstractTaxonomy')
		->toContain('location')
		->toContain('post');	
```

Expectation API is prettier 😄

2022-04-14 06:44 UTC, dingo-d commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('class BookTaxonomy extends AbstractTaxonomy', $generatedCPT);
Can you use expectation API here as well? Thanks 🙂

2022-04-14 06:45 UTC, dingo-d commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertArrayHasKey($key, $documentation);
https://pestphp.com/docs/expectations#tohavekeysarray-keys

2022-04-14 06:45 UTC, dingo-d commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('book', $generatedCPT);
Same as above

2022-04-14 06:45 UTC, dingo-d commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('book', $generatedCPT);
Same as the above

2022-04-14 06:53 UTC, dingo-d requested changes
Left some comments for the improvements, great job!

2022-04-15 10:27 UTC, iruzevic commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('post', $generatedCPT);
👍

2022-04-15 10:28 UTC, iruzevic commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('class BookTaxonomy extends AbstractTaxonomy', $generatedCPT);
👍

2022-04-15 10:36 UTC, iruzevic commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertArrayHasKey($key, $documentation);
👍

2022-04-15 10:36 UTC, iruzevic commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('book', $generatedCPT);
👍

2022-04-15 10:36 UTC, iruzevic commented on tests/CustomTaxonomy/TaxonomyCliTest.php
> +	$this->assertStringContainsString('book', $generatedCPT);
👍

2022-04-16 08:47 UTC, dingo-d commented on tests/CustomPostType/CustomPostTypeCliTest.php
> +	->toContain('$nouns[0]');
```suggestion
	expect($generatedCPT)
		->toContain('book')
		->toContain('books')
		->toContain('All books')
		->toContain('all books')
		->toContain('$labels')
		->toContain('$nouns[0]');
```

Indentation

2022-04-16 08:47 UTC, dingo-d commented on tests/CustomPostType/CustomPostTypeCliTest.php
> +	->toHaveKeys([$key, 'synopsis']);
```suggestion
	expect($documentation)
		->toBeArray($documentation)
		->toHaveKeys([$key, 'synopsis']);
```

Indentation

2022-04-16 08:47 UTC, dingo-d commented on tests/CustomPostType/CustomPostTypeCliTest.php
> +	->not->toContain('dashicons-analytics');
```suggestion
	expect($generatedCPT)
		->toContain('class BookPostType extends AbstractPostType')
		->toContain('Book')
		->toContain('book')
		->toContain('books')
		->toContain('post')
		->toContain('50')
		->toContain('dashicons-book')
		->not->toContain('dashicons-analytics');
```

Indentation

2022-04-16 08:47 UTC, dingo-d requested changes
Just a few minor indentation issues, otherwise looks good 👍🏼

2022-04-17 11:58 UTC, merged