Move reusable blocks menu to AdminMenus and create CLI command for its generation
infinum/eightshift-libs pull request #280
Opened 2022-04-15 12:45 UTC by simun-ivanac

# Description

Adding reusable blocks menu page is no longer positioned inside `Blocks.php`, but it's moved to its own class inside `AdminMenus`. Also, I created new CLI command to simplify its creation.

New command `wp boilerplate create_admin_reusable_blocks_menu` accepts next arguments:

- title _(Reusable Blocks)_
- menu_title _(Reusable Blocks)_
- capability _(edit_posts)_
- menu_icon _(dashicons-editor-table)_
- menu_position _(4)_

Regarding slug, it seems it's fixed `'edit.php?post_type=wp_block'` and you can't have multiple Reusable block menu pages. For that reason all arguments are optional.

If I overlooked something, feel free to point it out. 

And yes, I'll write tests :smile:

2022-04-15 13:15 UTC, mbmjertan submitted a review, later dismissed

2022-04-16 08:44 UTC, dingo-d commented on src/AdminMenus/AbstractAdminReusableBlocksMenu.php
> +<?php
Why do you need an abstract class for this? Do you plan on having multiple reusable block menus?

Abstract classes in libs are what is known as a [template method design pattern](https://en.wikipedia.org/wiki/Template_method_pattern). If you don't need to create different instances of the same thing, you don't need an abstract class 🙂

2022-04-16 08:45 UTC, dingo-d requested changes
Left one comment, otherwise good job 👍🏼

2022-04-19 13:09 UTC, iobrado submitted a review, later dismissed

2022-04-19 13:23 UTC, iruzevic requested changes
Not 100% happy with this approach. I will review it in dept later

2022-04-19 14:32 UTC, dingo-d commented
> Not 100% happy with this approach. I will review it in depth later

What approach would you prefer?

2022-04-25 06:49 UTC, iruzevic commented
Im retracting my last statement, this is ok. Great yob

2022-04-25 06:50 UTC, iruzevic approved these changes

2022-04-27 06:44 UTC, dingo-d commented on tests/AdminMenus/AdminReusableBlocksMenuCliTest.php
> +	expect($documentation[$key])->toBe('Generates reusable blocks admin menu class file.');
Expectations are chainable, meaning you can do:

```suggestion
	expect($documentation)->toBeArray()
		->toHaveKey($key)
		->toHaveKey('synopsis');
		
	expect($documentation[$key])->toBe('Generates reusable blocks admin menu class file.');
```

2022-04-27 14:20 UTC, dingo-d submitted a review, later dismissed
Just fix the phpstan issue 🙂 

Otherwise this looks great to me 👍🏼

2022-04-28 11:38 UTC, dingo-d approved these changes

2022-04-28 11:46 UTC, iruzevic approved these changes

2022-04-28 11:47 UTC, merged