Rename method arguments that are using reserved keywords
infinum/eightshift-libs pull request #282
Opened 2022-04-22 13:18 UTC by mbmjertan

# Description

Fixes #281 in all methods in Eightshift Libs, public, private and protected alike.

Note that in AbstractTaxonomyColumns and TaxonomyColumnsTest the variable is renamed to _string as there is no useful documentation about what that parameter is, and no implementation of this method exists in Eightshift Libs, so I can't check what's an appropriate name.

Also note that I have renamed them more aggressively than actually required, e.g. I renamed `$array`, which theoretically isn't reserved as a variable name.

# Linked documentation PR

https://www.php.net/manual/en/reserved.keywords.php
https://www.php.net/manual/en/reserved.other-reserved-words.php

2022-04-22 13:20 UTC, iruzevic submitted a review, later dismissed

2022-04-22 13:37 UTC, iruzevic approved these changes

2022-04-22 13:59 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +	public function prepareSlug(string $convert): string
Maybe more descriptive (expressive) names would be better?

Like `prepareSlug(convert: 'cool string')` reads odd. 

Maybe `prepareSlug($stringToConvert)` would be better?

2022-04-22 14:04 UTC, dingo-d commented on src/Columns/Taxonomy/AbstractTaxonomyColumns.php
> +	abstract public function renderColumnContent(string $_string, string $columnName, int $termId): string;
🙅🏼‍♂️

This is not good. 

```php
renderColumnContent(columName: 'bla', termId: 2, _string: 'what does _string mean??');
```

Change it to something more meaningfull, like `$blankString`? 

What is this used for anyways?

2022-04-22 14:08 UTC, dingo-d commented on src/Helpers/ObjectHelperTrait.php
> +	public static function isJson(string $check): bool
```suggestion
	public static function isJson(string $jsonString): bool
```

Is more clear when you type `isJson(jsonString: '....')`. Although I don't think this is needed since it's just one argument so maybe we could just leave it 🤷🏼‍♂️

2022-04-22 14:09 UTC, dingo-d commented on src/Helpers/ObjectHelperTrait.php
> +	public static function flattenArray(array $flatten): array
Similar to up, but we can leave it as it's just one argument.

2022-04-22 14:09 UTC, dingo-d commented on src/Helpers/ObjectHelperTrait.php
> +	public static function kebabToCamelCase(string $convert, string $separator = '-'): string
Again `$stringToConvert` reads more clearly if you want to use named arguments.

2022-04-22 14:10 UTC, dingo-d commented on tests/Columns/TaxonomyColumnsTest.php
> +		public function renderColumnContent(string $_string, string $columnName, int $termId): string
Again, no underscores please.

2022-04-22 14:11 UTC, dingo-d requested changes
Left some comments  👍🏼

2022-04-22 15:20 UTC, mbmjertan commented on src/Columns/Taxonomy/AbstractTaxonomyColumns.php
> +	abstract public function renderColumnContent(string $_string, string $columnName, int $termId): string;
> Note that in AbstractTaxonomyColumns and TaxonomyColumnsTest the variable is renamed to _string as there is no useful documentation about what that parameter is, and no implementation of this method exists in Eightshift Libs, so I can't check what's an appropriate name.

🤷 🤷 🤷

2022-04-22 15:21 UTC, mbmjertan commented on tests/Columns/TaxonomyColumnsTest.php
> +		public function renderColumnContent(string $_string, string $columnName, int $termId): string
> Note that in AbstractTaxonomyColumns and TaxonomyColumnsTest the variable is renamed to _string as there is no useful documentation about what that parameter is, and no implementation of this method exists in Eightshift Libs, so I can't check what's an appropriate name.

🤷

2022-05-12 12:59 UTC, dingo-d commented on src/Columns/Taxonomy/AbstractTaxonomyColumns.php
> +	abstract public function renderColumnContent(string $columnName, int $termId): string;
This is not correct: https://developer.wordpress.org/reference/hooks/manage_this-screen-taxonomy_custom_column/

The first argument of the filter is the thing that is filtered out, and the first argument is the custom column output

https://core.trac.wordpress.org/browser/tags/5.9/src/wp-admin/includes/class-wp-terms-list-table.php#L638

So the better naming would be 
```suggestion
	abstract public function renderColumnContent(string $columnOutput, string $columnName, int $termId): string;
```

2022-07-18 11:30 UTC, dingo-d commented
This will have to be rebased.

2022-07-21 09:12 UTC, dingo-d approved these changes
Looks good 👍🏼

2022-07-22 09:14 UTC, dadadavorin approved these changes
👍

2022-07-22 09:14 UTC, dadadavorin commented on src/Columns/Taxonomy/AbstractTaxonomyColumns.php
>  	 * Render the taxonomy column content in the custom taxonomy column
```suggestion
	 * Render the taxonomy column content in the custom taxonomy column.
```

2022-07-22 09:14 UTC, dadadavorin commented on src/Helpers/ObjectHelperTrait.php
>  	 * Convert string from kebab to camel case
```suggestion
	 * Convert string from kebab to camel case.
```

2022-07-22 09:14 UTC, dadadavorin commented on src/Menu/AbstractMenu.php
>  		// Check to see if any css modifiers were supplied.
```suggestion
		// Check to see if any CSS modifiers were supplied.
```

2022-07-22 10:13 UTC, dingo-d approved these changes

2022-07-22 11:08 UTC, dadadavorin approved these changes

2022-07-22 11:16 UTC, merged