Feature/web p
infinum/eightshift-libs pull request #287
Opened 2022-05-12 11:49 UTC by iruzevic

# Description

- Creating webP media
- Deleting webP media
- Updating webP media on media edit

2022-05-12 12:27 UTC, dadadavorin commented on package.json
>  	"description": "WordPress libs developed by Eightshift team to use in modern WordPress.",
```suggestion
	"description": "WordPress libs developed by Eightshift team for use in modern WordPress.",
```

2022-05-12 12:27 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	 * Delete all created webP media after original media is deleted.
```suggestion
	 * Delete all created WebP media after original media is deleted.
```

2022-05-12 12:28 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	 * Convert media to webP using file path.
```suggestion
	 * Convert media to WebP using file path.
```

2022-05-12 12:28 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +		// Replace the image name extension with the webP.
```suggestion
		// Replace the image name extension with the WebP.
```

2022-05-12 12:28 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +		// Create new webP image and store it to the same location.
```suggestion
		// Create new WebP image and store it to the same location.
```

2022-05-12 12:29 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	 * Delete webP media by path.
```suggestion
	 * Delete WebP media by path.
```

2022-05-12 12:29 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +		// Replace the image name extension with the webP.
```suggestion
		// Replace the image name extension with the WebP.
```

2022-05-12 12:29 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	 * Delete webP media sizes.
```suggestion
	 * Delete WebP media sizes.
```

2022-05-12 12:35 UTC, mbmjertan requested changes
I mostly really like this, but I have some concerns about the PNG to WebP conversion

2022-05-12 12:35 UTC, mbmjertan commented on CHANGELOG.md
> +- new WP-CLI command for reusable blocks
```suggestion
- new WP-CLI command for reusable blocks
- WebP conversion support
```

2022-05-12 12:35 UTC, mbmjertan commented on src/Media/AbstractMedia.php
> +	private const WEBP_QUALITY = 80;
I'm not sure that this should be a constant - maybe gather what's the quality of the original and use a minimum of the two, or something similar? E.g. - if someone uploads a 10% quality JPEG, this will generate a 80% quality WebP from that data, which will be larger, but with no discernible differences.

2022-05-12 12:35 UTC, mbmjertan commented on src/Media/AbstractMedia.php
> +				\ob_start();
Why is output buffering needed?

2022-05-12 12:35 UTC, mbmjertan commented on src/Media/AbstractMedia.php
> +				\ob_get_clean();
Why do you output png to the response payload here?

2022-05-12 12:55 UTC, dingo-d requested changes
Can you write tests for this?

2022-05-12 13:33 UTC, iruzevic commented on CHANGELOG.md
> +- Css variables combine output small fix if no blocks are added to dom.
this was from the previous PR so this is fixed

2022-05-12 13:37 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +				\ob_start();
because of the header in the line 158

2022-05-12 13:37 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +				\ob_get_clean();
i saw that in the documentation :D not sure

2022-05-12 13:37 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +		\imagedestroy($createdImage);
i will add additional checks tnx for the info

2022-05-12 13:49 UTC, mbmjertan commented on src/Media/AbstractMedia.php
> +				\ob_get_clean();
I'm not sure that's needed.

This code will create a GD image object from a file (`imagecreatefrompng`), set some flags on the GdObject (`imageplattetotruecolor`, `imagealphablending`, `imagesavealpha`), and then... set the response mimetype so the browser thinks it's getting an image back from the server and output the PNG to the browser? 

I believe this would work with lines 151, 158, 159 and 161 removed completely. There's no need to actually output the PNG file at this point, I think? This is not done for any other format here.

2022-05-16 07:22 UTC, dingo-d commented on src/Media/AbstractMedia.php
> +				\ob_start();
Maybe we could check the OB nesting level to make sure we are opening/closing the right one

https://www.php.net/manual/en/function.ob-get-level

?

2022-05-16 07:22 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +				\ob_start();
i have tested this and there is no need for this part at all, it works

2022-05-16 07:23 UTC, dingo-d commented on src/Media/AbstractMedia.php
> +				\ob_get_clean();
If the output is not needed, but the other things that were mentioned by Borna are needed, then the `ob_clean` should be used (after checking for the correct OB level - to be sure we're not closing some other OB by accident).

2022-05-16 09:16 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +				\ob_get_clean();
it turns out you don't need to create an additional image and no need for buffer. This work with out a problem

2022-05-16 10:36 UTC, mbmjertan commented on src/Media/AbstractMedia.php
> +	private const WEBP_QUALITY = 80;
Ah okay sure.

2022-05-16 10:37 UTC, dingo-d commented on src/Columns/Media/AbstractMediaColumns.php
> +abstract class AbstractMediaColumns implements ServiceInterface
Why does this need to be an abstract class? There are not going to be multiple media classes implementing different columns? In the case of CPT or CT, it makes sense to create a template pattern, in the case of media, having a single final class that gets copied over with CLI is a better approach.

2022-05-16 10:41 UTC, dingo-d commented on src/Columns/Media/WebPMediaColumnExample.php
> +			echo Components::existsWebPMedia($postId) ? '<span class="dashicons dashicons-saved"></span>' : '';
There are also yes/no icons, so that could be used here?

https://developer.wordpress.org/resource/dashicons/#icons-notifications

```suggestion
			$icon = Components::existsWebPMedia($postId) ? 'yes' : 'no';
			echo '<span class="dashicons dashicons-' . $icon . '"></span>'; // phpcs:ignore
```

2022-05-16 10:57 UTC, dingo-d commented on src/Columns/Media/AbstractMediaColumns.php
> +abstract class AbstractMediaColumns implements ServiceInterface
After a brief discussion, I saw the merit of this approach 👍🏼

2022-05-16 11:00 UTC, iruzevic commented on src/Columns/Media/AbstractMediaColumns.php
> +abstract class AbstractMediaColumns implements ServiceInterface
we agreed on Slack that it can be left like this, you have one class for each column like in users

2022-05-16 13:57 UTC, dingo-d approved these changes

2022-05-18 13:11 UTC, dingo-d commented on src/Media/RegenerateWebPMediaCli.php
> +			'longdesc' => "## EXAMPLES \n
We need this on all the other CLI commands 😍

2022-05-18 13:13 UTC, dingo-d commented on src/Media/RegenerateWebPMediaCli.php
> +			'post_status' => 'inherit',
Add `'perm' => 'readable'`

(https://developer.wordpress.org/reference/classes/wp_query/#user-contributed-notes)

2022-05-18 13:18 UTC, dingo-d commented on src/Media/RegenerateWebPMediaCli.php
> +			'post_mime_type' => \array_map(
Since you're basically just fetching the IDs of the attachments, you could use `'fields' => 'ids',`, and then manually provide the ID to the `get_the_title()` function when foreaching the result (no need to instantiate the loop and all that jazz).

2022-05-18 13:20 UTC, dingo-d commented on src/Media/RegenerateWebPMediaCli.php
> +		while ($theQuery->have_posts()) {
The same applies (they are the same queries).

2022-05-18 13:24 UTC, dingo-d commented on tests/Media/AbstractMediaTest.php
> +		->toBeNull();
```suggestion
	expect($mock)->toBeNull();
```

2022-05-19 08:09 UTC, dingo-d commented on src/Helpers/MediaTrait.php
> +		return (bool) \get_option(UseWebPMediaCli::USE_WEBP_MEDIA_OPTION_NAME, 'true');
```suggestion
		return (bool) \get_option(UseWebPMediaCli::USE_WEBP_MEDIA_OPTION_NAME, true);
```

2022-05-19 08:18 UTC, dingo-d commented on src/Media/UseWebPMediaCli.php
> +		if ((bool) \get_option(self::USE_WEBP_MEDIA_OPTION_NAME)) {
```suggestion
		if (\get_option(self::USE_WEBP_MEDIA_OPTION_NAME)) {
```

2022-05-19 08:18 UTC, dingo-d requested changes
Some really minor changes left.

2022-05-19 08:54 UTC, dadadavorin requested changes
Really cool 💪 🤩  Just a few grammar corrections.

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/AbstractMediaColumns.php
> + * Media columns abstract class file
```suggestion
 * Media columns abstract class file.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/AbstractMediaColumns.php
> +	 * Render the media column content in the custom media column
```suggestion
	 * Render the media column content in the custom media column.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/AbstractMediaColumns.php
> +	 * Make media columns sortable
```suggestion
	 * Make media columns sortable.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/WebPMediaColumnCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WPCLI command doc.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/WebPMediaColumnExample.php
> +	 * Render the media column content in the custom media column
```suggestion
	 * Render the media column content in the custom media column.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Columns/Media/WebPMediaColumnExample.php
> +	 * Make media columns sortable
```suggestion
	 * Make media columns sortable.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	 * Generate webP media images.
```suggestion
	 * Generate WebP media images.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Media/AbstractMedia.php
> +	public const WEBP_ALLOWED_EXT = ['gif', 'jpg', 'jpeg', 'png', 'bmp'];
what happens if someone uploads WebP?

2022-05-19 08:54 UTC, dadadavorin commented on src/Media/MediaWebPTrait.php
> +	 * Generate webP media images - sizes.
```suggestion
	 * Generate WebP media images - sizes.
```

2022-05-19 08:54 UTC, dadadavorin commented on src/Media/MediaWebPTrait.php
> +	 * Generate webP media images - original size.
```suggestion
	 * Generate WebP media images - original size.
```

2022-05-19 08:59 UTC, iruzevic commented on src/Media/AbstractMedia.php
> +	public const WEBP_ALLOWED_EXT = ['gif', 'jpg', 'jpeg', 'png', 'bmp'];
good point

2022-05-19 09:15 UTC, mbmjertan approved these changes
Looks great!

2022-05-19 09:31 UTC, mbmjertan approved these changes

2022-05-19 10:37 UTC, dadadavorin approved these changes

2022-05-19 10:56 UTC, dingo-d commented on src/Columns/Media/AbstractMediaColumns.php
> + * Media columns abstract class file.
Just a comment, but by docs standards, you don't need a full stop at the end of the short doc, only after the description part in the dec block.

2022-05-19 10:57 UTC, dingo-d submitted a review, later dismissed

2022-05-19 10:58 UTC, dingo-d commented
Weird that the phpstan is failing, that should be fixed in the earlier commit. I suggest just putting the bem menu to ignored path in the phpstan config.

2022-05-19 11:08 UTC, dingo-d commented on src/Helpers/MediaTrait.php
> +	 * @return array<string>
This will throw an error in phpstan (99% sure) because you don't have a list, but a key-value array.

It should be `array<string, string>`. Not sure if the empty array would be an issue for this tbh

2022-05-24 09:09 UTC, merged