Feature/cli update
infinum/eightshift-libs pull request #291
Opened 2022-05-24 07:02 UTC by iruzevic

# Description

- added examples, options, defaults on all commands.
- restructured all commands to follow the parent commands standard
- refactored a few commands to use template strings for replacement
- refactored tests
- refactored all comments and descriptions
- added new cli parent classes for better documentation
- added links to documentation and GH examples

# Screenshots / Videos

![Screenshot 2022-05-23 at 09 16 25](http
![Screenshot 2022-05-20 at 14 59 01](https://user-images.githubusercontent.com/23283324/169968791-c565b626-5e7d-4a10-9049-49499030d6df.png)
s://user-images.githubusercontent.com/23283324/169968778-1c661f0e-0e83-43b4-aea9-3b75808d30a2.png)
![Screenshot 2022-05-23 at 09 20 28](https://user-images.githubusercontent.com/23283324/169968786-f6aad6b9-d8ac-4682-ae12-391995d10d8a.png)

2022-05-24 10:19 UTC, iruzevic commented on src/AdminMenus/AdminMenuCli.php
> +			'title' => 'Test Title',
there is no need for them because I used some simple helpers to provide the data

2022-05-24 10:20 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +	}
```suggestion
	/**
	 * Get one argument.
	 *
	 * Use assocArgs props and fallback to default if missing.
	 *
	 * @param array<string, string> $arguments Array of args to check.
	 * @param string $key Argument name to check.
	 *
	 * @return string
	 */
	public function getArg(array $arguments, string $key): string
	{
		return isset($arguments[$key]) ? (string) $arguments[$key] : $this->getDefaultArg($key);
	}
```

2022-05-24 10:22 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +	}
Can you just make this an abstract method? Are there some CLI commands that don't have default arguments?

2022-05-24 10:25 UTC, dingo-d commented on src/Cli/AbstractCli.php
>  	 * @return array<string, mixed>
Can we be more specific about what this argument array contains? Can it really contain everything or just strings, numbers, booleans?

Because I'm unsure if the `$args[$i] ?? $value` check is valid on line 178 (if it's a non nullable entity this will never default to `$value`).

2022-05-24 10:26 UTC, dingo-d commented on src/Cli/AbstractCli.php
> +		return isset($args[$key]) ? (string) $args[$key] : '';
If the arguments are always strings, casting isn't necessary.

Are the argument values strings, or can they be something else?

2022-05-24 10:26 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +	}
yep there are bunch of them that is why I left this like this

2022-05-24 10:31 UTC, dingo-d commented on tests/WpCli/WpCliTest.php
> +	expect($this->customCommand->getDoc())->toBeArray();
This is terse 😂 

No love for checking the output? 😢

2022-05-24 10:32 UTC, dingo-d commented on tests/View/EscapedViewCliTest.php
> +	$this->assertStringNotContainsString('someRandomMethod', $generatedEscapedView);
```suggestion
	expect($generatedEscapedView)->not-> toContain('someRandomMethod');
```

2022-05-24 10:38 UTC, dingo-d commented on tests/Cli/CliInitProjectTest.php
> +	$this->assertSame('project', $commandName);
```suggestion
	expect($commandName)
		->toBeString()
		->toBe('project');
```

2022-05-24 10:39 UTC, dingo-d commented on tests/CiExclude/CiExcludeCliTest.php
> +	$this->assertStringContainsString('ci_exclude', $result);
```suggestion
	expect($result)->toContain('ci_exclude');
```

2022-05-24 10:40 UTC, dingo-d commented on tests/Blocks/BlockWrapperCliTest.php
> +	$this->assertStringContainsString('wrapper', $result);
```suggestion
	expect($result)->toContain('wrapper');
```

2022-05-24 10:40 UTC, dingo-d commented on tests/Blocks/BlockCliTest.php
> +	$this->assertStringContainsString('block', $result);
```suggestion
	expect($result)->toContain('block');
```

2022-05-24 12:39 UTC, dingo-d commented on src/AdminMenus/AdminSubMenuCli.php
> +// phpcs:ignoreFile Generic.Files.LineLength.TooLong
You have effectively disabled this for all the other files, because you didn't re-enable the phpcs for this rule 🙈 

Either exclude files in the `phpcs.xml.dist`, or on the lines that are problematic please.

Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset#the-annotated-sample-file

2022-05-24 12:50 UTC, dingo-d commented on src/Cli/ParentGroups/CliBlocks.php
> +class CliBlocks extends WP_CLI_Command
Would it be better to maybe have just one of these classes and constants inside instead of multiple classes that only hold constants inside?

Not sure what is gained with this granulation 🤷🏼‍♂️

2022-05-24 12:51 UTC, dingo-d commented on src/Cli/TopLevelGroup/CliBoilerplate.php
> +class CliBoilerplate extends WP_CLI_Command
Could the class constants in the parent groups be here?

2022-05-24 12:56 UTC, dingo-d requested changes
I've reviewed 66/108 files 😅 

Most of the files are basically the same, so I don't think I need to go with a fine-tooth comb over it.

The comments I've left are more oriented towards the architecture/structure of the lib.

Great job on splitting the commands and adding examples 🙂  👍🏼

2022-05-24 13:03 UTC, dingo-d commented on src/AdminMenus/AdminSubMenuCli.php
> +// phpcs:ignoreFile Generic.Files.LineLength.TooLong
Correct! My bad, I replaced it with disable and enable.

Still, I'd add the pattern exclusion in the ruleset:

```xml
	<rule ref="Generic.Files.LineLength">
		<exclude-pattern>*/src/**/*Cli.php</exclude-pattern>
		<properties>
			<property name="lineLimit" value="180" />
			<property name="ignoreComments" value="true" />
		</properties>
	</rule>
```

than have the comment on top of every CLI file 😉

2022-05-24 19:04 UTC, iobrado requested changes
Awesome work! I found some typos in descriptions and added suggestions to fix them.

2022-05-24 19:04 UTC, iobrado commented on src/Build/BuildCli.php
> +				# Create service class:
```suggestion
				# Copy file:
```

2022-05-24 19:04 UTC, iobrado commented on src/Build/BuildCli.php
> +				Service class will be created from this example:
```suggestion
				File will be created from this example:
```

2022-05-25 09:10 UTC, iruzevic commented on src/AdminMenus/AdminSubMenuCli.php
> +// phpcs:ignoreFile Generic.Files.LineLength.TooLong
awesome I like the rule approach :D

2022-05-25 09:11 UTC, iruzevic commented on src/Cli/ParentGroups/CliBlocks.php
> +class CliBlocks extends WP_CLI_Command
I have tried that first but the problem is how WP-CLI parses the doc comments on the commands and this is the only way I could make them work.

2022-05-25 09:12 UTC, iruzevic commented on src/Cli/TopLevelGroup/CliBoilerplate.php
> +class CliBoilerplate extends WP_CLI_Command
answered in the https://github.com/infinum/eightshift-libs/pull/291#discussion_r881417229

2022-05-25 09:13 UTC, iruzevic commented on tests/WpCli/WpCliTest.php
> +	expect($this->customCommand->getDoc())->toBeArray();
I don't see the point checking the docs array, we have nothing to gain with that

2022-05-25 09:18 UTC, iruzevic commented on src/Cli/AbstractCli.php
>  	 * @return array<string, mixed>
Updated int, string and bool

2022-05-25 09:20 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +		return isset($args[$key]) ? (string) $args[$key] : '';
agreed

2022-05-25 10:43 UTC, iruzevic commented on src/Cli/AbstractCli.php
> +		return isset($args[$key]) ? (string) $args[$key] : '';
i have tested this and it turns out you can get string,int or bool here but the output should always be string. So this type hint here is ok

2022-05-25 11:48 UTC, iobrado approved these changes

2022-05-26 05:24 UTC, dingo-d commented on tests/WpCli/WpCliTest.php
> +	expect($this->customCommand->getDoc())->toBeArray();
Good for keeping track of changes 😉

2022-05-26 05:25 UTC, dingo-d commented
@iruzevic just check the `wp-json` for routes with this branch, I got some WP_CLI error message when I loaded it for testing.

2022-06-06 08:21 UTC, dingo-d commented on src/Geolocation/GeolocationExample.php
> +		$path = __DIR__ . '/geoip2.phar';
Directory separator

2022-06-06 08:21 UTC, dingo-d commented on src/Geolocation/GeolocationExample.php
> +		$path = __DIR__ . '/GeoLite2-Country.mmdb';
Same as up

2022-06-06 08:24 UTC, dingo-d requested changes
Geolocation is not tested. Since this is a bigger PR it would be good to focus on having tests 🙂

2022-06-06 08:50 UTC, iruzevic commented on src/Geolocation/GeolocationExample.php
> +		$path = __DIR__ . '/GeoLite2-Country.mmdb';
fixed

2022-06-06 08:50 UTC, merged