Geolocation service class
infinum/eightshift-libs pull request #296
Opened 2022-05-25 08:43 UTC by iruzevic

# Description

- new service class for geolocation used to provide cookie set for user location based on the GeoLite2 Country database.

2022-05-25 10:31 UTC, dadadavorin approved these changes
Nice 👍  As I am aware - we are using the MaxMind database to compare the IP address to the country codes, and once downloaded to the project it stays the same.

Maybe it would be better to fetch the database from time to time, so it stays updated (WooCommerce does it like this if we turn on the geolocation in settings)?

2022-05-25 10:45 UTC, iruzevic commented
> Nice 👍 As I am aware - we are using the MaxMind database to compare the IP address to the country codes, and once downloaded to the project it stays the same.
> 
> Maybe it would be better to fetch the database from time to time, so it stays updated (WooCommerce does it like this if we turn on the geolocation in settings)?

how you handle db fetching is up to you on the project. I agree that this should be done but it is per project basis

2022-05-25 11:58 UTC, iobrado approved these changes
Found 2 typos 🙂

2022-05-25 11:58 UTC, iobrado commented on src/Geolocation/GeolocationExample.php
> +			return new Exception(\sprintf(\esc_html__('Missing Geolocation phar on this locaiton %s', 'eightshift-libs'), $path));
```suggestion
			return new Exception(\sprintf(\esc_html__('Missing Geolocation phar on this location %s', 'eightshift-libs'), $path));
```

2022-05-25 11:58 UTC, iobrado commented on src/Geolocation/GeolocationExample.php
> +			return new Exception(\sprintf(\esc_html__('Missing Geolocation database on this locaiton %s', 'eightshift-libs'), $path));
```suggestion
			return new Exception(\sprintf(\esc_html__('Missing Geolocation database on this location %s', 'eightshift-libs'), $path));
```

2022-05-26 07:10 UTC, goranalkovic-infinum commented on src/Geolocation/AbstractGeolocation.php
> +	 * Gets ip address by manual. General used for development and testing.
```suggestion
	 * Gets an IP address manually. Generally used for development and testing.
```

2022-05-26 07:13 UTC, goranalkovic-infinum commented on src/Geolocation/AbstractGeolocation.php
> +	 * Get geolocation 2 digit code proivided by the project.
```suggestion
	 * Gets the 2-digit location code provided by the project.
```

2022-05-26 07:18 UTC, goranalkovic-infinum commented on src/Geolocation/Readme.md
> +We use [GeoIP2-php library](https://github.com/maxmind/GeoIP2-php) to get the correct countries based on the IP address of the user that we compare with the countries list that we get from the [DataH
```suggestion
We use the [GeoIP2-php library](https://github.com/maxmind/GeoIP2-php) to get the user's location (country) based on their IP address. List of the countries is compared with the [DataHub list](https://datahub.io/core/country-list).
```

2022-05-26 07:46 UTC, mbmjertan requested changes
Also some typos. 😀

2022-05-26 07:46 UTC, mbmjertan commented on src/Geolocation/AbstractGeolocation.php
> +		if ($adittionalLocaitons) {
```suggestion
		$additionalLocations = $this->getAdditionalCountries();
		if ($additionalLocations) {
```

2022-05-26 07:46 UTC, mbmjertan commented on src/Geolocation/AbstractGeolocation.php
> +				$adittionalLocaitons
```suggestion
				$additionalLocations
```

2022-06-01 09:34 UTC, volfkarlo approved these changes

2022-06-03 07:16 UTC, merged