WIP: adding loadmore route
infinum/eightshift-libs pull request #297
Opened 2022-05-26 13:20 UTC by iruzevic

⚠️ DO NOT REVIEW YET

# Description

- added new load more route that converts WP_Query args to REST-API route.
- used for load more feature

# Linked PR

This is a linked PR with frontend libs: https://github.com/infinum/eightshift-frontend-libs/pull/625

2022-06-03 12:31 UTC, iobrado approved these changes

2022-06-03 12:31 UTC, iobrado commented on src/DynamicData/AbstractDynamicData.php
> +		// Prevend accidental issues.
```suggestion
		// Prevent accidental issues.
```

2022-06-06 07:51 UTC, dingo-d commented on src/DynamicData/AbstractDynamicData.php
> +	public function getDynamicDataAjax(): string
Can we create a custom rest route for this instead? 🙏🏼

2022-06-06 07:52 UTC, dingo-d requested changes
It would be better to use REST instead of AJAX. Easier to handle permissions and other security issues...

2022-06-07 11:28 UTC, iruzevic commented on src/Enqueue/Theme/EnqueueThemeExample.php
> +		$sep = \DIRECTORY_SEPARATOR;
hehehe nice :D I got PTSP of this separator, when I see slash it goes DIRECTORY_SEPARATOR :D

2022-06-07 11:29 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +abstract class AbstractLoadMore extends AbstractRoute implements CallableRouteInterface
What's the idea behind this abstract class?

If you want to have multiple load more routs, you'd extend it, but you'd still need to modify the response and the actual query logic for loading more posts/pages/entities?

I'm not sure I understand how you'd implement this.

Can you explain it?

2022-06-07 11:31 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +abstract class AbstractLoadMore extends AbstractRoute implements CallableRouteInterface
The idea is to have one rest-route in your project where you map the response to your component and nothing else. In general you can have multiple load more instances of routes but in 99 % cases this will not be the case. 

In your project you will have only this src/Rest/Routes/LoadMore/LoadMoreRouteExample.php

2022-06-07 11:43 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +abstract class AbstractLoadMore extends AbstractRoute implements CallableRouteInterface
Maybe this will help
https://github.com/infinum/eightshift-frontend-libs/tree/feature/block-featured-content/blocks/init/src/Blocks/components/load-more/docs

2022-06-07 12:10 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +abstract class AbstractLoadMore extends AbstractRoute implements CallableRouteInterface
Ok, but in that case, this can just be a concrete `final` class with all the logic inside? 

I think that would be better.

We should limit abstract classes to templates, where it makes sense to use them. Always favoring composition over inheritance where possible.

2022-06-07 12:14 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +				400
Can this code be extracted out the `WP_Error` object?

2022-06-07 12:20 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +				\esc_html__('Your request is missing query param. Query param should be a valid WP_Query arguments.', 'eightshift-boilerplate')
```suggestion
				\esc_html__('Your request is missing query parameters. Query parameters should be a valid WP_Query arguments array.', 'eightshift-boilerplate')
```

2022-06-07 12:20 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +				\esc_html__('Your request is missing type param. This is used to filter whate response will the method return.', 'eightshift-boilerplate')
```suggestion
				\esc_html__('Your request is missing type parameter. This is used to filter out what kind of response will the method return.', 'eightshift-boilerplate')
```

2022-06-07 12:21 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +					'Your request is missing initialItems param. This is used to determin number of items to load and what items to exclude from new requests.',
```suggestion
					'Your request is missing initialItems parameter. This is used to determine the number of items to load and what items to exclude from new requests.',
```

2022-06-07 12:22 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +		// Create new query to modify of url load.
```suggestion
		// Create a new query to modify the load more URL.
```

Is this correct intention of the comment? I'm not sure I understood the original comment.

2022-06-07 12:27 UTC, dingo-d commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +		\wp_reset_postdata();
Is this necessary? You have the `$newQuery` in the previous method. Can this be used to get the `$postsNumber`?

Just pass it as a parameter and you won't need to initialize the query again.

2022-06-07 12:28 UTC, dingo-d commented on src/Rest/Routes/LoadMore/LoadMoreRouteExample.php
> +			'methods' => static::CREATABLE,
Why is this `POST`?

You are retrieving the posts from the DB, this should be a `GET` (`READABLE`) endpoint.

2022-06-07 12:29 UTC, dingo-d requested changes
Left a few comments. The REST API approach looks much better 😄

2022-06-07 14:48 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +				400
I think not https://developer.wordpress.org/reference/classes/wp_error/

2022-06-07 14:48 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +		// Create new query to modify of url load.
i have updated the comment

2022-06-07 14:48 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +		// In case on url load update per page to new value.
i have updated the comment

2022-06-08 07:10 UTC, iruzevic commented on src/Rest/Routes/LoadMore/AbstractLoadMore.php
> +abstract class AbstractLoadMore extends AbstractRoute implements CallableRouteInterface
done

2022-06-08 09:00 UTC, dingo-d reviewed
From an architectural perspective looks good. We need tests for this.

Also, before merging, either do a squash merge so that we don't have a lot of useless commits, or rebase to clean up the commits a bit please 🙂

2022-06-08 09:57 UTC, merged