Adding variations to store
infinum/eightshift-libs pull request #299
Opened 2022-06-03 11:14 UTC by iruzevic

# Description

- added variations to the store.

2022-06-03 11:15 UTC, goranalkovic-infinum submitted a review, later dismissed

2022-06-03 11:20 UTC, iobrado requested changes
Noticed just one typo 🙂

2022-06-03 11:20 UTC, iobrado commented on src/Helpers/StoreTrait.php
> +			self::getvariations(),
```suggestion
			self::getVariations(),
```

2022-06-03 11:32 UTC, iobrado approved these changes

2022-06-03 15:27 UTC, mbmjertan submitted a review, later dismissed

2022-06-06 07:46 UTC, dingo-d approved these changes

2022-06-06 07:47 UTC, dingo-d requested changes
Left one comment, also check the CI failures

2022-06-06 08:58 UTC, iruzevic commented
fixed

2022-06-06 08:59 UTC, merged