Feature/tests
infinum/eightshift-libs pull request #302
Opened 2022-06-13 12:14 UTC by iruzevic

# Description

- fixing and updating tests

2022-06-13 12:23 UTC, dingo-d commented on patchwork.json
>      "system",
Can you check which ones are being redefined from BrainMonkey `when` and just remove the ones we are not mocking?

2022-06-13 12:25 UTC, dingo-d commented on src/Geolocation/AbstractGeolocation.php
> +	 * Mock setCookie method for testing reasons.
```suggestion
	 * Wrapper method for the native PHP setcookie function.
	 *
	 * We are using a wrapper because we cannot easily mock the setcookie function from PHP.
	 * This way, we can just mock our implementation during tests.
```

2022-06-13 12:26 UTC, mbmjertan commented on src/Geolocation/AbstractGeolocation.php
> +	 * Mock setCookie method for testing reasons.
```suggestion
	 * Wrap setCookie method to allow for better mocking in tests.
```

2022-06-13 12:27 UTC, dingo-d commented on tests/Geolocation/AbstractGeolocationTest.php
> +	expect($countries[3]['value'])->toEqual('AF');
```suggestion
	expect($countries[0])->toBeArray()->toHaveKeys(['label', 'value', 'group'])
		->and(count($countries))->toEqual(252)
		->and($countries[0]['value'])->toEqual('europe')
		->and($countries[1]['value'])->toEqual('european-union')
		->and($countries[2]['value'])->toEqual('ex-yugoslavia')
		->and($countries[3]['value'])->toEqual('AF');
```

2022-06-13 12:28 UTC, dingo-d commented on tests/Geolocation/AbstractGeolocationTest.php
> +	expect($countries[252]['value'])->toEqual('test');
```suggestion
	expect(count($countries))->toEqual(253)
		->and($countries[0]['value'])->toEqual('europe')
		->and($countries[252]['value'])->toEqual('test');
```

2022-06-13 12:30 UTC, dingo-d commented on tests/Helpers.php
> +	return __DIR__ . "/data/{$path}";
```suggestion
	$ds = \DIRECTORY_SEPARATOR;

	return __DIR__ . "{$ds}data{$ds}{$path}";
```

2022-06-13 12:30 UTC, dingo-d requested changes
Left some minor comments, great job 👍🏼

2022-06-13 12:30 UTC, mbmjertan commented on src/Geolocation/AbstractGeolocation.php
> +	 * Mock setCookie method for testing reasons.
Denis's suggestion is better, ignore.

2022-06-13 12:35 UTC, mbmjertan commented on tests/Geolocation/AbstractGeolocationTest.php
> +	});
I think you should probably return in this closure, see http://docs.mockery.io/en/latest/reference/expectations.html?highlight=withArgs#argument-matching-with-closures

2022-06-28 10:18 UTC, dingo-d approved these changes

2022-06-28 10:19 UTC, merged