Feature/cli
infinum/eightshift-libs pull request #308
Opened 2022-07-05 11:23 UTC by iruzevic

# Description

- WP CLI update, adding parent command names, adding examples, fixing resources, etc.
- Updating internal links to use helper for paths so it can be used in tests and on real project
- Fixing tests

# Screenshots / Videos
![Screenshot 2022-07-05 at 09 23 24 (2)](https://user-images.githubusercontent.com/23283324/177316706-275a8ff0-47d6-483a-b8af-8105be1ee830.png)
![Screenshot 2022-07-05 at 09 23 24 (3)](https://user-images.githubusercontent.com/23283324/177316719-ff905c0d-c2c7-463e-bf13-faf60c0cf1a1.png)
![Screenshot 2022-07-05 at 09 24 46](https://user-images.githubusercontent.com/23283324/177316724-c7a51dae-22fc-47c6-92ed-5d9d04499da7.png)
![Screenshot 2022-07-05 at 10 18 06](https://user-images.githubusercontent.com/23283324/177316729-2f5c9c42-8c1c-497b-9148-31693e8020ec.png)

2022-07-05 13:21 UTC, dingo-d commented on src/Blocks/AbstractBlocksCli.php
> +	 * Determin if item has dependencies and output helper commands.
```suggestion
	 * Determine if the item has dependencies and output helper commands.
```

2022-07-05 13:24 UTC, dingo-d commented on src/Blocks/UseComponentCli.php
> +					'description' => 'Specify component name. You can specify multiple components by comma separator.',
```suggestion
					'description' => 'Specify component name. You can specify multiple components (separate them with comma).',
```

2022-07-05 13:25 UTC, dingo-d commented on src/Blocks/UseGlobalAssetsCli.php
> +				Used to copy pre-created global assets from our library to your project. After copying you can modify it in any way you see fit.
```suggestion
				Used to copy pre-created global assets from our library to your project. After copying you can modify them in any way you see fit.
```

2022-07-05 13:26 UTC, dingo-d commented on src/Blocks/UseManifestCli.php
> +				This file is a block editor main setting file where you can find color, option and much more.
```suggestion
				This file is a block editor's main setting file where you can find the color, options, and much more.
```

2022-07-05 13:27 UTC, dingo-d commented on src/Blocks/UseManifestCli.php
> +	public function __invoke(array $args, array $assocArgs) // phpcs:ignore
```suggestion
	public function __invoke(array $args, array $assocArgs)
```

2022-07-05 13:29 UTC, dingo-d commented on src/Blocks/UseVariationCli.php
> +	public function __invoke(array $args, array $assocArgs) // phpcs:ignore
```suggestion
	public function __invoke(array $args, array $assocArgs)
```

2022-07-05 13:29 UTC, dingo-d commented on src/Blocks/UseWrapperCli.php
> +	public function __invoke(array $args, array $assocArgs) // phpcs:ignore
```suggestion
	public function __invoke(array $args, array $assocArgs)
```

2022-07-05 13:37 UTC, dingo-d commented on src/CiExclude/CiExcludeCli.php
> +			->outputWrite($path, 'ci-exclude.txt', $assocArgs);
We can delete this as this is no longer used anywhere.

2022-07-05 13:47 UTC, dingo-d commented on src/Cli/README.md
> +You can run this commands by mocking them in the tests.
I think you can just remove this readme, don't think it serves a purpose 🤷🏼‍♂️

2022-07-05 13:51 UTC, dingo-d commented on src/Build/BuildCli.php
> +			->outputWrite($path, 'build.sh', $assocArgs);
This file can be deleted, we're not using it anywhere.

2022-07-05 13:53 UTC, dingo-d commented on src/Cli/ParentGroups/CliBlocks.php
> + *    $ wp boilerplate blocks use_block --name='paragraph'
Can we rename these commands to be something like

```bash
wp boilerplate use block --name='paragraph'
```

?

Reads more fluently.

Since we are overhauling all the commands, it makes sense to fix this as well.

2022-07-05 14:27 UTC, dingo-d commented on src/Blocks/UseAssetsCli.php
> +	public function __invoke(array $args, array $assocArgs) // phpcs:ignore
I was annoyed by this so I released the 1.6.0 version of es coding standards.

You should be able to do the following in the `phpcs.xml.dist`:

```xml
<!-- Add additional extending CLI classes. -->
<rule ref="Eightshift.Commenting.FunctionComment">
    <properties>
        <property name="allowedExtendedClasses" type="array">
            <element value="AbstractCli"/>
            <element value="AbstractBlocksCli"/>
        </property>
    </properties>
</rule>
```

Which should enable you to remove the `// phpcs:ignore` comment from the `__invoke()` magic methods.

Just check all these new CLI methods and what class they are extending and add it to the above list as an `<element>` element in the xml file.

Once you add those, remove the comment and see if it errors out.

2022-07-05 15:11 UTC, dadadavorin reviewed
Wow, amazing work! 🤩 Found few typos/grammar improvements...

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitProjectCli.php
> + * Class that registers WPCLI command initial setup of theme project.
```suggestion
 * Class that registers WP-CLI command initial setup of theme project.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitProjectCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WP-CLI command doc.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitProjectCli.php
> +			$this->cliLog('We have moved everything you need, to start creating your awesome WordPress project. Please type `npm start` in your terminal to kickstart your assets bundle process.', "M");
```suggestion
			$this->cliLog('We have moved everything you need to start creating your awesome WordPress project. Please type `npm start` in your terminal to kickstart your assets bundle process.', "M");
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> + * Class that registers WPCLI command initial setup of theme project.
```suggestion
 * Class that registers WP-CLI command initial setup of theme project.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> +	 * All classes for initial theme setup for project
```suggestion
	 * All classes for initial theme setup for project.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> +	 * Get WPCLI command parent name
```suggestion
	 * Get WP-CLI command parent name.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> +	 * Get WPCLI command name
```suggestion
	 * Get WP-CLI command name.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WP-CLI command doc.
```

2022-07-05 15:11 UTC, dadadavorin commented on src/Init/InitThemeCli.php
> +			$this->cliLog('We have moved everything you need, to start creating your awesome WordPress theme. Please type `npm start` in your terminal to kickstart your assets bundle process.', "M");
```suggestion
			$this->cliLog('We have moved everything you need to start creating your awesome WordPress theme. Please type `npm start` in your terminal to kickstart your assets bundle process.', "M");
```

2022-07-05 15:11 UTC, dadadavorin commented on tests/Helpers.php
> + * Get projects root path for mocks.
```suggestion
 * Get project root path for mocks.
```

2022-07-06 07:16 UTC, iruzevic commented on src/Build/BuildExample.php
> +	cd 'wp-content/%project_type%/%project_name%';
noup removed it

2022-07-06 07:16 UTC, iruzevic commented on src/CiExclude/CiExcludeCli.php
> +			->outputWrite($path, 'ci-exclude.txt', $assocArgs);
removed

2022-07-06 07:16 UTC, iruzevic commented on src/CiExclude/CiExcludeExample.php
> +
removed

2022-07-06 07:16 UTC, iruzevic commented on src/Cli/README.md
> +You can run this commands by mocking them in the tests.
I would leave it if someone comes that they know how to test

2022-07-06 11:42 UTC, dingo-d commented on src/AdminMenus/AdminMenuCli.php
> -				$ wp boilerplate {$this->getCommandParentName()} {$this->getCommandName()} --title='Content' --menu_title='content' --capability='edit_posts' --menu_slug='es-content'
Can you test replacing the `prepareLongDesc` with a heredoc?

https://github.com/infinum/eightshift-libs/blob/fix-install-plugins-method/src/Setup/PluginManageCli.php#L111

2022-07-06 11:44 UTC, dingo-d commented on src/Helpers/Components.php
> +				$path =  self::joinPaths($libsPath);
```suggestion
				$path = self::joinPaths($libsPath);
```

2022-07-06 11:45 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([...$testsDataPath, $assetsPath]);
```suggestion
					$path = self::joinPaths([...$testsDataPath, $assetsPath]);
```

2022-07-06 11:45 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([...$testsDataPath, ...$blocksPath, $assetsPath]);
```suggestion
					$path = self::joinPaths([...$testsDataPath, ...$blocksPath, $assetsPath]);
```

2022-07-06 11:45 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([...$testsDataPath, $storybookPath]);
```suggestion
					$path = self::joinPaths([...$testsDataPath, $storybookPath]);
```

2022-07-06 11:45 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([...$testsDataPath, ...$blocksPath]);
```suggestion
					$path = self::joinPaths([...$testsDataPath, ...$blocksPath]);
```

2022-07-06 11:46 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([$cliOutputPath, $assetsPath]);
```suggestion
					$path = self::joinPaths([$cliOutputPath, $assetsPath]);
```

2022-07-06 11:46 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([$cliOutputPath, ...$blocksPath, $assetsPath]);
```suggestion
					$path = self::joinPaths([$cliOutputPath, ...$blocksPath, $assetsPath]);
```

2022-07-06 11:46 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([$cliOutputPath, ".{$storybookPath}"]);
```suggestion
					$path = self::joinPaths([$cliOutputPath, ".{$storybookPath}"]);
```

2022-07-06 11:48 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([...$testsDataPath, ...$blocksPath, $name]);
```suggestion
					$path = self::joinPaths([...$testsDataPath, ...$blocksPath, $name]);
```

2022-07-06 11:48 UTC, dingo-d commented on src/Helpers/Components.php
> +					$path =  self::joinPaths([$cliOutputPath, ...$blocksPath, $name]);
```suggestion
					$path = self::joinPaths([$cliOutputPath, ...$blocksPath, $name]);
```

2022-07-06 12:00 UTC, dingo-d commented on tests/Helpers/AttributesTraitTest.php
> +	buildTestBlocks();
Try to see if you can use `uses` to bind this to just this test case.

https://pestphp.com/docs/underlying-test-case#uses

2022-07-06 15:18 UTC, dingo-d requested changes
Left a few comments to fix. Nothing major imo.

Can we change all the command arguments so that they are using `-` instead of `_` as a separator?
That's the way the default CLI commands use.

2022-07-06 21:32 UTC, iruzevic commented on src/Blocks/BlocksCli.php
> +		return 'create blocks_class';
done

2022-07-07 07:48 UTC, dingo-d commented on src/AdminMenus/AdminMenuCli.php
> -				$ wp boilerplate {$this->getCommandParentName()} {$this->getCommandName()} --title='Content' --menu_title='content' --capability='edit_posts' --menu_slug='es-content'
Oh, I see it now! Wasn't aware that the headings will be parsed that way 👍🏼

2022-07-07 11:09 UTC, iobrado requested changes
Most impressive PR 👏  I left suggestions to fix some typos I stumbled upon.

2022-07-07 11:09 UTC, iobrado commented on tests/Init/InitBlocksCliTest.php
> +	// $output = \file_get_contents(Components::getProjectPaths('blocksDestination', "Blocks.php"));
Do you need this commented out part or can it be removed?

2022-07-07 13:14 UTC, iruzevic commented on tests/Init/InitBlocksCliTest.php
> +	// $output = \file_get_contents(Components::getProjectPaths('blocksDestination', "Blocks.php"));
fixed

2022-07-07 15:21 UTC, dadadavorin submitted a review, later dismissed
Looks good 👍  Just found a few typos..

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/BlocksCli.php
>  				This file is a main entrypoint for all our block editor setup.
```suggestion
				This file is a main entry point for all our block editor setup.
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseAssetsCli.php
> +	 * Get WPCLI command parent name
```suggestion
	 * Get WP-CLI command parent name
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseAssetsCli.php
> +	 * Get WPCLI command name
```suggestion
	 * Get WP-CLI command name
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseAssetsCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WP-CLI command doc
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseGlobalAssetsCli.php
> + * Class that registers WPCLI command for Blocks global assets.
```suggestion
 * Class that registers WP-CLI command for Blocks global assets.
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseGlobalAssetsCli.php
> +	 * Get WPCLI command parent name
```suggestion
	 * Get WP-CLI command parent name
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseGlobalAssetsCli.php
> +	 * Get WPCLI command name
```suggestion
	 * Get WP-CLI command name
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseGlobalAssetsCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WP-CLI command doc
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseManifestCli.php
> + * Class that registers WPCLI command for Blocks Manifest.
```suggestion
 * Class that registers WP-CLI command for Blocks Manifest.
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseManifestCli.php
> +	 * Get WPCLI command parent name
```suggestion
	 * Get WP-CLI command parent name
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Blocks/UseWrapperCli.php
> +	 * Get WPCLI command doc
```suggestion
	 * Get WP-CLI command doc
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Init/InitAllCli.php
> + * Class that registers WPCLI command initial setup for all.
```suggestion
 * Class that registers WP-CLI command initial setup for all.
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Init/InitAllCli.php
> +	 * Get WPCLI command parent name.
```suggestion
	 * Get WP-CLI command parent name.
```

2022-07-07 15:21 UTC, dadadavorin commented on src/Init/InitAllCli.php
> +	 * Get WPCLI command name.
```suggestion
	 * Get WP-CLI command name.
```

2022-07-07 15:58 UTC, mbmjertan requested changes
Reviewed files changed, apart from tests, as it's been quite a task to review this. Congratulations, this was an amazing endeavor. I've left some comments about phrasing, and some tips for a potentially better approach in some places, but I don't take issue with this code. Great work.

2022-07-07 15:58 UTC, mbmjertan commented on src/Blocks/AbstractBlocksCli.php
> +		$isFile = \strpos($name, '.') !== false;
This is not a valid assumption to have on UNIX systems, e.g. `/etc/hosts` is a file. All files that'll be moved probably have an extension, but this is not a valid way to check whether something is a file.

Rather use [`is_file`](https://www.php.net/manual/en/function.is-file.php) and pass the file path to it.

2022-07-07 15:58 UTC, mbmjertan commented on src/Blocks/BlocksCli.php
>  				This file is a main entrypoint for all our block editor setup.
"for all our block editor setup" also doesn't tell much, maybe rephrase that part as well

2022-07-07 15:58 UTC, mbmjertan commented on src/Helpers/Components.php
> +	 * Paths join
```suggestion
	 * Join paths.
```

#wordOrderMatters

2022-07-07 15:58 UTC, mbmjertan commented on src/Init/InitAllCli.php
> +			$this->cliLog('--------------------------------------------------');
Do you copy/paste these separators? Maybe we should have a helper for that as well, so it's consistent.

2022-07-07 15:58 UTC, mbmjertan commented on src/Init/InitBlocksCli.php
> +			$this->cliLog('Happy developing!', "M");
As previously

2022-07-07 15:58 UTC, mbmjertan commented on src/Init/InitProjectCli.php
> +		}
As above

2022-07-07 15:58 UTC, mbmjertan commented on src/Init/InitThemeCli.php
> +}
As above

2022-07-08 06:56 UTC, iruzevic commented on src/Init/InitAllCli.php
> +			$this->cliLog('Happy developing!', "M");
I have created an issue for this https://github.com/infinum/eightshift-libs/issues/310

2022-07-08 06:56 UTC, merged