Fix plugins cli
infinum/eightshift-libs pull request #323
Opened 2022-07-30 08:22 UTC by dingo-d

# Description

Updated #303 PR.

This PR adds the new plugin manage CLI method that should replace the update method.

Should cover all the cases: install/update from wp.org (core), GitHub, and paid plugins. Also, has a --delete-plugins flag so that the only deletion can be made of the plugins which are not in the setup.json.

# Issues

For some reason, the WPCLI mocks are not getting called, which is causing the tests to fail. Feel free to play around with this to see what could be the cause of it. Once this is fixed the PR can be moved from draft to ready. 

PR comments are welcomed, but will be addressed when I get back from 🌴

2022-08-11 15:08 UTC, mbmjertan commented on src/Setup/PluginManageCli.php
> +			return $name;
When can this be the case on Github? 👀

2022-08-11 15:08 UTC, mbmjertan commented on src/Setup/PluginManageCli.php
> +		return $splitName[\count($splitName) - 1];
This and L345 will probably cause an issue? The repo owner is missing in the release URL that way?

E. g., this is the release URL for the latest Forms release: https://github.com/infinum/eightshift-forms/releases/download/1.4.1-alpha/release.zip - note that both `infinum` and `eightshift-forms` are constituent - this wouldn't be the case with this code if I'm not mistaken

2022-08-12 06:07 UTC, dingo-d commented on src/Setup/PluginManageCli.php
> +			return $name;
Tbh not sure, this method is inside the deploy task so I took it from there. I guess we need some manual testing to see if this is necessary or not.

2022-08-12 06:09 UTC, dingo-d commented on src/Setup/PluginManageCli.php
> +		return $splitName[\count($splitName) - 1];
Again, not sure. I'd love it if somebody could test this in a real example (that is, using this branch when setting up a project, then filling up the `setup.json` file, and running the scripts) 🙏🏼 

All of the code here is in the deployment scripts (just modified to be a bit cleaner).

2022-08-12 08:04 UTC, gabriel-glo requested changes
A few smaller things to fix. 
This brach should definitely be tested locally by at least two people before merge.

2022-08-12 11:13 UTC, mbmjertan commented
Tried it with GitHub and core plugins on a local project, found some issues:

## Wrong path to `setup.json` when running `plugin_manage`

Tries to look for `setup.json` in `wp-content/themes`, not the theme folder itself:

```
mariobornamjertan@Marios-MacBook-Pro ~/d/m/w/t/myproj> wp boilerplate run plugin_manage
Error: File missing on the path: /Users/mariobornamjertan/dev/multisitestandup/wp-content/themes/setup.json.
mariobornamjertan@Marios-MacBook-Pro ~/d/m/w/t/myproj [1]> pwd
/Users/mariobornamjertan/dev/multisitestandup/wp-content/themes/myproj
```

## Shell errors when running `plugin_manage`

```
mariobornamjertan@Marios-MacBook-Pro ~/d/m/w/t/myproj> wp boilerplate run plugin_manage
Remove plugins
Plugin akismet removed
Plugin hello removed
Plugin wp-rocket removed
Plugin advanced-cache.php removed
Success: Plugin query-monitor installed
Success: Plugin taxonomy-terms-order installed
Success: Plugin redirection installed
Success: Plugin wordfence installed
Success: Plugin wp-security-audit-log installed
Success: Plugin wp-crontrol installed
Success: Plugin wp-mail-smtp installed
Success: Plugin wordpress-seo installed
Downloading installation package from https://github.com/infinum/eightshift-forms/releases/download/1.3.0/release.zip...
Unpacking the package...
Installing the plugin...
Removing the old version of the plugin...
Plugin updated successfully.
Success: Installed 1 of 1 plugins.
sh: -c: line 0: syntax error near unexpected token `do'
sh: -c: line 0: `'/opt/homebrew/Cellar/php@7.4/7.4.30/bin/php' /usr/local/bin/wp  for f in ./wp-content/plugins/release*/; do rsync -avh --delete "$f" "./wp-content/plugins/eightshift-forms/" && rm -rf "$f"; done'
```

----

Regarding the Github plugin URL discussion, I misread that `shortName` was used instead of `name` in the URL. Sorry for the confusion 🙈

2022-08-16 08:03 UTC, dingo-d commented on src/Setup/PluginManageCli.php
> +					EOT,
Since this isn't a `longdesc`, the only way to have a nice break line when checking the synopsis of the command is using [heredoc syntax](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc).

2022-08-16 08:06 UTC, dingo-d commented
@mbmjertan thanks for the test, I'll try to reproduce this and fix the issues 👍🏼

2022-08-16 09:58 UTC, dingo-d commented on src/Setup/PluginManageCli.php
> +			return $name;
Indeed this part is not needed at all.

2022-08-16 09:59 UTC, dingo-d commented
@mbmjertan Can you check if this works for you now? I've fixed the tests and parts that were failing, and also removed the unneeded rsync call

2022-09-19 08:36 UTC, iruzevic approved these changes

2022-09-22 07:31 UTC, iruzevic approved these changes

2022-09-22 08:01 UTC, gabriel-glo approved these changes

2022-09-22 08:49 UTC, merged