Add improved CI
infinum/eightshift-libs pull request #332
Opened 2022-08-24 17:11 UTC by szepeviktor

# Description

Removes **huge** amount of mix code styling ❌

# Screenshots / Videos

![kép](https://user-images.githubusercontent.com/952007/186480615-3b841eec-be50-4662-a5f1-c11ec9364a08.png)

# Linked documentation PR

All my knowledge 🧠

2022-08-24 17:21 UTC, szepeviktor commented
BTW There are a lot of PSR-4 loading problems in tests.

May I send another PR?

```
Class Tests\Unit\Columns\TaxonomyColumnMock located in ./tests/Unit/Columns/TaxonomyColumnsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Columns\MediaColumnMock located in ./tests/Unit/Columns/Media/MediaColumnsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Columns\UserColumnMock located in ./tests/Unit/Columns/UsersColumnsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Columns\PostTypeColumnMock located in ./tests/Unit/Columns/PostTypeColumnsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Cli\AbstractTest located in ./tests/Unit/Cli/AbstractCliTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Helpers\MockErrorLogger located in ./tests/Unit/Helpers/ErrorLoggerTraitTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Helpers\MockObjectHelper located in ./tests/Unit/Helpers/ObjectHelperTraitTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Main\MainTest located in ./tests/Unit/Main/AbstractMainTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Unit\Main\MainCompiledTest located in ./tests/Unit/Main/AbstractMainTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Datasets\Autowiring\Invalid\DoesNotExist\ServiceWithInvalidNamespace located in ./tests/Datasets/Autowiring/Invalid/ServiceWithInvalidNamespace.php does not comply with psr-4 autoloading standard. Skipping.
```

2022-08-25 07:11 UTC, dingo-d requested changes
Love the additions! Thank you for the work on improving the codebase.

I have left some questions and suggestions in the comments.

Just to ask here: Is it possible to have two separate workflows but have one depend on another like in the `needs` part? I love to separate concerns, make the workflow file a bit easier to read than one massive file (although the current one you propose does have huge improvement).

2022-08-25 07:22 UTC, szepeviktor commented on .github/workflows/integrate.yml
> +name: "Integrate"
"CI" ==== continuous >integrat<ion

2022-08-25 07:24 UTC, szepeviktor commented on .github/workflows/integrate.yml
> +          ! LC_ALL=C.UTF-8 find . -type f -name "*.php" -print0 | xargs -0 -- grep -PHn "[^\t -~]"
This check for strings like `"Žoljom"` which is valid in all programing langues.

2022-08-25 07:26 UTC, szepeviktor commented on .github/workflows/integrate.yml
> +    name: "4️⃣ Coding Standards"
@dingo-d So you would like to add the word "checks" seven times to this UI?

![kép](https://user-images.githubusercontent.com/952007/186602012-49fdb070-99db-420f-b209-b56441fdffb4.png)

2022-08-25 07:37 UTC, szepeviktor commented on .github/workflows/integrate.yml
> +    name: "4️⃣ Coding Standards"
Jobs are containers for steps, they don't do anything.
Steps in a job do different things, one of them is a check.

2022-08-25 07:46 UTC, szepeviktor commented
> Is it possible to have two separate workflows but have one depend on another like in the needs part?

```yaml
on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - "completed"

jobs:
  step-name:
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    steps:
      - run: |
          echo 'The triggering workflow passed'
```

📖 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

2022-08-25 07:53 UTC, dingo-d commented on .github/workflows/integrate.yml
> +          ! LC_ALL=C.UTF-8 find . -type f -name "*.php" -print0 | xargs -0 -- grep -PHn "[^\t -~]"
Yes, but the check is for non printable ASCII characters, which sounds like a syntax check to me 🤷🏼‍♂️

2022-08-25 07:54 UTC, dingo-d commented on .github/workflows/integrate.yml
> +    name: "4️⃣ Coding Standards"
Yeah, the above would read nicer with checks to me (except for the tests one ofc).

2022-08-25 07:55 UTC, dingo-d commented
> > Is it possible to have two separate workflows but have one depend on another like in the needs part?
> 
> Yes, it is. It makes very hard to understand CI.
> 
> ```yaml
> on:
>   workflow_run:
>     workflows:
>       - "Build"
>     types:
>       - "completed"
> 
> jobs:
>   my-job-id:
>     if: "${{ github.event.workflow_run.conclusion == 'success' }}"
>     steps:
>       - run: |
>           echo 'The triggering workflow passed'
> ```
> 
> 📖 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

Yeah, I think that would make things a bit harder to understand. We can leave the one main file 👍🏼

2022-08-25 08:53 UTC, mbmjertan commented on .editorconfig
> +# https://EditorConfig.org
A basic `.editorconfig` would be great to have IMO, as we could set default settings for indentation. Other coding style settings can be set in the IDE directly, but this is something that's already mandated on the project level with coding standards, so I see no resason why not to provide an `.editorconfig`

2022-08-25 08:55 UTC, mbmjertan commented on .github/workflows/integrate.yml
> +          ! LC_ALL=C.UTF-8 find . -type f -name "*.php" -print0 | xargs -0 -- grep -PHn "[^\t -~]"
It is a syntax check, but not a syntax error 🤷

2022-08-25 09:04 UTC, szepeviktor commented
All your wishes came true!

2022-08-25 09:06 UTC, szepeviktor commented on .editorconfig
> +block_comment_end = */
You're welcome.

2022-08-25 09:09 UTC, szepeviktor commented on .github/workflows/integrate.yml
> +          ! LC_ALL=C.UTF-8 find . -type f -name "*.php" -print0 | xargs -0 -- grep -PHn "[^\t -~]"
This is a low-level stuff, "Byte-level" how I call it.
I've moved this step to "Syntax errors checks"

2022-08-25 09:36 UTC, dingo-d approved these changes
Amazing, thank you very much for these improvements 👍🏼

2022-08-25 11:37 UTC, mbmjertan approved these changes
Amazing! Thank you for your contribution 🎉 😄 🙇

2022-08-25 11:58 UTC, merged