adding geolocation corrections
infinum/eightshift-libs pull request #341
Opened 2022-09-27 21:27 UTC by iruzevic

# Description

## Added
- New function for providing cookie expiration time.
- New file providing geolocation with WP-Rocket cache

2022-09-29 09:49 UTC, mbmjertan commented on src/Geolocation/Readme.md
> +By providing custom custom to advanced-cached.php file you will be able to detect geolocation and set cookies before the cached version is provided.
```suggestion
By providing a custom function in the advanced-cached.php file, you will be able to detect geolocation and set cookies before the cached version is provided.
```

2022-09-29 09:53 UTC, piqusy requested changes
Great work 🚀 Left some semantic & spelling suggestions.

2022-09-29 09:53 UTC, piqusy commented on src/Geolocation/Readme.md
> +WP-Rocket plugin provides the options/hooks to fix this. By using this hook `rocket_advanced_cache_file` we are able to inject our custom function in the page generation process inside the `wp-conten
```suggestion
WP-Rocket plugin provides options/hooks to fix this. By using hook `rocket_advanced_cache_file` we are able to inject our custom function in the page generation process inside the `wp-content/advanced-cache.php` file. By modifying this file we can detect users geolocation from the IP and set the cookie manually before the page is loaded. This way WP-Rocket can detect that cookie and provide the necessary cache. Below is the process of setting it:
```

2022-09-29 09:53 UTC, piqusy commented on src/Geolocation/Readme.md
> +You must provide the list of cookies that will be used as a dynamic cookie to generate cached versions.
```suggestion
You must provide the list of cookies that will be used as dynamic cookies to generate cached versions.
```

2022-09-29 09:53 UTC, piqusy commented on src/Geolocation/Readme.md
> +By providing custom custom to advanced-cached.php file you will be able to detect geolocation and set cookies before the cached version is provided.
```suggestion
By providing custom function to advanced-cached.php file you will be able to detect geolocation and set cookies before the cached version is provided.
```

2022-09-29 09:53 UTC, piqusy commented on src/Geolocation/Readme.md
> +If you have installed Geolocation.php class in your project and you have this filter set, make sure you disable it, or provide the check to be disabled when WP-Rocket cache plugin is active.
```suggestion
If you have installed Geolocation.php class in your project and you have this filter set, make sure to disable it, or provide the check to be disabled when WP-Rocket cache plugin is active.
```

2022-09-29 11:07 UTC, piqusy submitted a review, later dismissed

2022-09-30 07:28 UTC, volfkarlo approved these changes
Seems good! 😄

2022-10-03 07:54 UTC, dingo-d requested changes
Left some small remarks. Generally looks ok 👍🏼

2022-10-03 07:54 UTC, dingo-d commented on composer.json
> +		"standards:check": "composer test:standards"
Why duplicate the commands you have under the `test` namespace?

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/AbstractGeolocation.php
> +				$this->getGeolocationExpiration(),
Like the abstraction 👍🏼 more clear what the intention is.

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> +When geolocation is used in combination with WP-Rocket plugin it will not work by default because the cookie is set after the page is loaded and at that point it is too late to provide content.
```suggestion
When geolocation is used in combination with the WP-Rocket plugin it will not work by default because the cookie is set after the page is loaded and at that point, it is too late to provide alternative content.
```

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> +WP-Rocket plugin provides options/hooks to fix this. By using hook `rocket_advanced_cache_file` we are able to inject our custom function in the page generation process inside the `wp-content/advance
```suggestion
WP-Rocket plugin provides options/hooks to fix this. By using the `rocket_advanced_cache_file` hook we are able to inject our custom function into the page generation process inside the `wp-content/advanced-cache.php` file. By modifying this file we can detect the users' geolocation from the IP and set the cookie manually before the page is loaded. This way WP-Rocket can detect that cookie and provide the necessary cache. Below is the process of setting it:
```

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> +By providing a custom function in the advanced-cached.php file, you will be able to detect geolocation and set cookies before the cached version is provided.
```suggestion
By providing a custom function in the `advanced-cached.php` file, you will be able to detect geolocation and set cookies before the cached version is provided.
```

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> +For `$esFormsPath` variable you must provide the absolute path to the `geolocationDetect.php` file in vendor.
```suggestion
For the `$esFormsPath` variable you must provide the absolute path to the `geolocationDetect.php` file located in the `vendor` folder.
```

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> + */
```suggestion
/**
 * Add geolocation function in the advance-cache.php config file on plugin activation
 *
 * Used only with Nginx web servers.
 *
 * @param string $content Original file output.
 */
```

2022-10-03 07:54 UTC, dingo-d commented on src/Geolocation/Readme.md
> +If you have installed Geolocation.php class in your project and you have this filter set, make sure to disable it, or provide the check to be disabled when WP-Rocket cache plugin is active.
```suggestion
If you have installed Geolocation.php class in your project and you have this filter set, make sure to disable it, or provide the check to be disabled when the WP-Rocket cache plugin is active.
```

2022-10-03 07:57 UTC, iruzevic commented on composer.json
> +		"standards:check": "composer test:standards"
because we have that command in 30+ projects and libs, and only this project has it changed. I don't have the problem of having it like "test:" but I would like to retain the old command as well.

2022-10-03 08:00 UTC, dingo-d commented on composer.json
> +		"standards:check": "composer test:standards"
I was planning on changing this on other projects as well. I really don't like this change here, especially since it's a separate project on its own and the composer scripts are not shared between the projects.

We shouldn't revert the better change, instead we should improve other projects to have the better change...

2022-10-03 13:05 UTC, dingo-d approved these changes

2022-10-03 13:10 UTC, merged