Reusable header/footer updates and CLI improvements
infinum/eightshift-libs pull request #363
Opened 2023-06-06 08:43 UTC by goranalkovic-infinum

> **Note**
The commits make it look way scarier than it is (it was mostly just trying things out 😄)

Changes:
- added new CLI command for initializing reusable header/footer (settings page for picking blocks, and default blocks)
- added new helper to render nice alert "windows"
- revamped some CLI command outputs and error outputs

![image](https://github.com/infinum/eightshift-libs/assets/77000136/8c95f426-80be-4a89-adea-5248ba4c5075)
![image](https://github.com/infinum/eightshift-libs/assets/77000136/e3945738-a05b-45e3-a906-fcd6e48f66ce)
![image](https://github.com/infinum/eightshift-libs/assets/77000136/84958068-e395-446c-915b-02bc16f764f1)

2023-06-07 12:20 UTC, iobrado approved these changes

2023-06-07 14:37 UTC, piqusy requested changes
Nice work 👏🏼 
I left one suggestion 😉 

Other than that, I'm wondering why the header and footer need to be so closely coupled / created with the same command?

2023-06-12 12:57 UTC, goranalkovic-infinum commented
> Other than that, I'm wondering why the header and footer need to be so closely coupled / created with the same command?

They're this closely coupled because... well I was a bit lazy 😄

If you want to have both header and footer pickers on one screen, it would be a bit complicated to check whether you have none, one or both already added, and then try to patch files with the second picker.

That would also complicated things a bit on the Boilerplate side, where you would maybe need to check if it's even there.

Because every site will have some kind of a header and footer (and it's really ease to remove if for some reason it's not needed), it's combined into 1 command. (also, before full-auto theme setup I didn't want to have user run too many extra commands to set it up)

2023-06-12 13:00 UTC, iobrado submitted a review, later dismissed

2023-06-12 13:05 UTC, iobrado approved these changes

2023-06-12 13:44 UTC, piqusy approved these changes

2023-06-13 06:18 UTC, iruzevic approved these changes

2023-06-13 06:18 UTC, merged