WIP : PHP8
infinum/eightshift-libs pull request #381
Opened 2023-10-26 07:51 UTC by iruzevic

⚠️ PHP8 preparation branch

# Description

- updating composer packages
- fixing stan and lint issues
- updating composer command names
- Denis fixes for standards
- adding missing type hinting

2023-10-26 11:32 UTC, dingo-d requested changes
Left some minor comments.

The thing I'm more worried about is the change in the component rendering.
Several tests are failing (some of which are easy to fix), but for some, I'm not sure the behavior is correct, or at least this new feature has kinda complicated testing.

Because inside the tests you don't have WordPress, the test for the feature could be actually correct, but this new exception would make it seem like it's not correct.

For instance, the following test:

```php
test('Asserts that rendering a component works', function () {
	$results = Components::render('button', []);

	expect($results)
		->not->toBeEmpty()
		->toContain('Hello!');
});
```

This should be correct (confirming that rendering actually works), but this will now throw an exception: `You are not allowed to access paths outside of themes or plugins folder!`

So I think that either this should be fixed in test setup, to somehow 'trick' the code to think that during tests we are inside WordPress theme/plugin, or at the code level with a flag 🤷🏼‍♂️

2023-10-26 11:32 UTC, dingo-d commented on .github/workflows/integrate.yml
>            - "lowest"
I think you can remove `lowest`, and then remove extra includes below with allowed failures. The tests should pass fine if that condition is removed (unless the code is legit broken ofc 😂 ).

2023-10-26 11:32 UTC, dingo-d commented on composer.json
>  		"szepeviktor/phpstan-wordpress": "^1.0.3",
```suggestion
		"szepeviktor/phpstan-wordpress": "^1.3",
```

2023-10-27 12:36 UTC, iruzevic commented on .github/workflows/integrate.yml
>            - "lowest"
removed

2023-10-27 12:36 UTC, iruzevic commented
> Left some minor comments.
> 
> The thing I'm more worried about is the change in the component rendering. Several tests are failing (some of which are easy to fix), but for some, I'm not sure the behavior is correct, or at least this new feature has kinda complicated testing.
> 
> Because inside the tests you don't have WordPress, the test for the feature could be actually correct, but this new exception would make it seem like it's not correct.
> 
> For instance, the following test:
> 
> ```
> test('Asserts that rendering a component works', function () {
> 	$results = Components::render('button', []);
> 
> 	expect($results)
> 		->not->toBeEmpty()
> 		->toContain('Hello!');
> });
> ```
> 
> This should be correct (confirming that rendering actually works), but this will now throw an exception: `You are not allowed to access paths outside of themes or plugins folder!`
> 
> So I think that either this should be fixed in test setup, to somehow 'trick' the code to think that during tests we are inside WordPress theme/plugin, or at the code level with a flag 🤷🏼‍♂️

I have fixed all the tests

2023-10-27 12:43 UTC, iruzevic commented on .github/workflows/integrate.yml
>            - "lowest"
not sure if I did it correctly, but all check are passing, can you please check

2023-10-27 12:46 UTC, dingo-d commented on .github/workflows/integrate.yml
> +    continue-on-error: ${{ matrix.allowed_failure }}
```suggestion
```

There is no `allowed_failure` key in the matrix so this can be removed.

2023-10-27 12:47 UTC, dingo-d commented on .github/workflows/integrate.yml
> +    continue-on-error: ${{ matrix.allowed_failure }}
You were faster than me 😄

2023-10-27 12:49 UTC, iruzevic commented on .github/workflows/integrate.yml
> +    continue-on-error: ${{ matrix.allowed_failure }}
It is all passing now

2023-10-27 12:50 UTC, iruzevic commented
I can't any errors in the tests, linters or stan. Also There are no issues in the debug log. Npx is working as expected :D I thing this setup is ready for PHP8.2. WooCommerce is also working :D

2023-10-30 08:44 UTC, dadadavorin approved these changes

2023-10-30 08:44 UTC, dadadavorin commented on src/Db/DbImport.php
> +			$errorClass::cliError('Urls key is missing or empty.');
URLs

2023-10-30 08:44 UTC, dadadavorin commented on src/Db/DbImport.php
> +			$errorClass::cliError("{$from} key is missing or empty in urls.");
same

2023-10-30 08:44 UTC, dadadavorin commented on src/Db/DbImport.php
> +			$errorClass::cliError("{$to} key is missing or empty in urls.");
also

2023-10-30 08:45 UTC, dadadavorin approved these changes

2023-10-30 08:46 UTC, piqusy requested changes
PHP8 🎆 
Nice work, left a few wording suggetions

2023-10-30 09:26 UTC, dingo-d requested changes
Left some minor comments and questions.

2023-10-30 09:26 UTC, dingo-d commented on tests/BaseTest.php
> +use WP_Theme;
Don't see this being used anywhere in the test 🤔

2023-10-30 09:26 UTC, dingo-d commented on src/Blocks/AbstractBlocksCli.php
> +
```suggestion
```

2023-10-30 09:26 UTC, dingo-d commented on tests/Unit/Exception/InvalidBlockTest.php
> +		->and('Global Blocks settings manifest.json is missing a key called namespace. This key prefixes all block names.')
Is this message changed in the CLI command? If not, this change would fail the test.

2023-10-30 09:26 UTC, dingo-d commented on tests/Unit/Exception/InvalidBlockTest.php
> +		->and("Wrapper blocks settings manifest.json is missing on this location: {$manifestPath}.")
If this is changed in the CLI, then the message should be changed as well.

2023-10-30 09:26 UTC, dingo-d commented on src/Misc/VersionCli.php
> +<?php
This CLI command should be covered by tests.

2023-10-30 09:26 UTC, dingo-d commented on src/Enqueue/Theme/AbstractEnqueueTheme.php
> +		if (!$this->isEnqueueStylesUsed($hook)) {
I'm not sure I understand how this works, if the method will return `true` no matter what 👀

2023-10-30 09:26 UTC, dingo-d commented on src/Enqueue/Blocks/AbstractEnqueueBlocks.php
> +		if (!$this->isEnqueueBlockFrontendStyleUsed($hook)) {
How does this work, if all the method does is return `true`?

2023-10-30 09:26 UTC, dingo-d commented on src/Enqueue/Admin/AbstractEnqueueAdmin.php
> +		if (!$this->isEnqueueScriptsUsed($hook)) {
Same as with the other helpers. This always returns `true`, not sure how this works 🤷🏼‍♂️

2023-10-30 10:10 UTC, iruzevic commented on src/Db/DbImport.php
> +			$errorClass::cliError('Urls key is missing or empty.');
"urls" is a key in the setup.json so if i put it all caps someone might thing this is the key name. I would like it as is

2023-10-30 10:11 UTC, iruzevic commented on tests/Unit/Exception/InvalidBlockTest.php
> +		->and("Wrapper blocks settings manifest.json is missing on this location: {$manifestPath}.")
tnx but I would leave this as is for now. We have a ticket that will check all copy

2023-10-30 10:12 UTC, iruzevic commented on tests/Unit/Exception/InvalidBlockTest.php
> +		->and('Global Blocks settings manifest.json is missing a key called namespace. This key prefixes all block names.')
the same as before

2023-10-30 10:12 UTC, iruzevic commented on tests/Unit/Cli/CliHelpersTest.php
> +	$class::cliError('Some random cli error happened');
these are tests copy corrections are not necessary here

2023-10-30 10:13 UTC, iruzevic commented on src/Blocks/AbstractBlocksCli.php
> +
tnx

2023-10-30 10:14 UTC, iruzevic commented on tests/BaseTest.php
> +use WP_Theme;
removed

2023-10-30 10:14 UTC, iruzevic commented on src/Misc/VersionCli.php
> +<?php
agreed will be in the next PR

2023-10-30 10:17 UTC, iruzevic commented on src/Enqueue/Blocks/AbstractEnqueueBlocks.php
> +		if (!$this->isEnqueueBlockFrontendStyleUsed($hook)) {
You can extend this function in your project and provide a condition when this script will be loaded. Hook param is passed from the original action. 

In general $hook is filled only in admin scripts not on the frontend. I have added this method on all scripts so you can potentially define every script where you would like to use it

2023-10-30 10:30 UTC, piqusy submitted a review, later dismissed

2023-10-30 12:40 UTC, kancijan submitted a review, later dismissed

2023-10-30 21:46 UTC, mbmjertan requested changes

2023-10-30 21:46 UTC, mbmjertan commented on src/Db/DbImport.php
> +		};
why is `CliHelpers` a trait to begin with? converting classes to traits just to instantiate anonymous classes implementing them to call trait methods smells a lot. if you want ping me and we can talk about what you want to achieve with this

2023-10-30 21:46 UTC, mbmjertan commented on tests/BaseTest.php
> +
Just use the `AllowDynamicProperties` class attribute https://php.watch/versions/8.2/AllowDynamicProperties 
```suggestion
```

2023-10-30 21:46 UTC, mbmjertan commented on tests/BaseTest.php
>  class BaseTest extends TestCase
```suggestion
#[AllowDynamicProperties]
class BaseTest extends TestCase
```

2023-10-30 21:46 UTC, mbmjertan commented on tests/Unit/Helpers/AttributesTraitTest.php
> +})->throws(Exception::class, 'buttonAlign key does not exist in the button block manifest. If you are using additional components, check if you used the correct block/component prefix in your attribu
better sentence order?
```suggestion
})->throws(Exception::class, 'buttonAlign key does not exist in the button block manifest. Please check your implementation. If you are using additional components, check if you used the correct block/component prefix in your attribute name.');
```

2023-10-30 21:46 UTC, mbmjertan commented on src/Cli/Cli.php
>  		AdminMenuCli::class,
consider some simple autodiscovery for this, e.g. separate deeper namespaces and getting a list of classes in it. I understand that you rarely add any CLI commands but this seems like it's not the Eightshift way

2023-10-30 22:10 UTC, dingo-d commented on tests/BaseTest.php
> +
When PHP 9 comes out, the attribute won't matter, because deprecations would turn to errors, so it's safer to just add these (granted the internals might just decide to just leave the attribute working even in PHP 9, but this is still a safer route).

I was thinking of just adding one `$mock` for all the mocked classes in the tests, but that would take me some time to check, cover and change, and this was faster 🤷🏼‍♂️

2023-10-30 22:11 UTC, dingo-d commented on tests/Unit/Helpers/AttributesTraitTest.php
> +})->throws(Exception::class, 'buttonAlign key does not exist in the button block manifest. If you are using additional components, check if you used the correct block/component prefix in your attribu
You'd have to also change the exception message in the exception itself otherwise the test would fail.

2023-10-30 22:12 UTC, dingo-d commented on src/Cli/Cli.php
>  		AdminMenuCli::class,
I was also wondering if this could be done in a smarter way, perhaps `glob`ing classes somehow, and just listing the `Cli` ones 🤔

2023-10-31 07:02 UTC, iruzevic commented on src/Db/DbImport.php
> +		};
I believe that while it may be possible to refactor this code for the sake of making it cleaner, it would not provide any significant value at this point. I will create an issue for it and revisit it later. Thank you for your comment.

2023-10-31 07:03 UTC, iruzevic commented on src/Db/DbImport.php
> +		};
https://github.com/infinum/eightshift-libs/issues/382

2023-10-31 07:05 UTC, iruzevic commented on tests/BaseTest.php
> +
thx for the suggestion but as these are tests I won't spend much time on refactoring this, and I agree with Denis

2023-10-31 07:08 UTC, iruzevic commented on tests/Unit/Helpers/AttributesTraitTest.php
> +})->throws(Exception::class, 'buttonAlign key does not exist in the button block manifest. If you are using additional components, check if you used the correct block/component prefix in your attribu
tnx, changed in both places

2023-10-31 07:09 UTC, iruzevic commented on src/Cli/Cli.php
>  		AdminMenuCli::class,
agree I will create a ticket for this https://github.com/infinum/eightshift-libs/issues/383

2023-10-31 07:11 UTC, kancijan approved these changes

2023-10-31 07:15 UTC, goranalkovic-infinum approved these changes

2023-10-31 08:02 UTC, dingo-d commented on tests/BaseTest.php
> +
Don't get me wrong, even tests should be clean, refactored, and taken care of, as they can acquire code cruft as time goes by (like this is a clear example of it). It's just that sometimes you need to do the 'dirty' fix to push the feature through, and fix it later 😄 

_We'll fix it in post_ 😂

2023-10-31 08:25 UTC, piqusy approved these changes

2023-10-31 08:26 UTC, iobrado approved these changes

2023-10-31 09:20 UTC, mbmjertan commented on tests/BaseTest.php
> +
The RFC somewhat implies that they will leave the attribute available in PHP 9, so I think that's a viable course of action. Either way, magic setters (__set) aren't deprecated and you could make a trait that allows setting dynamic properties. 

I understand your point of view and irrelevance of this in the grand scheme of things - but I believe we (Eightshift and friends) should strive to have a clean and understandable codebase.

2023-10-31 09:27 UTC, iruzevic commented on tests/BaseTest.php
> +
agreed I will create a issue for this https://github.com/infinum/eightshift-libs/issues/384

2023-11-06 08:25 UTC, merged