Libs 8.0.0 release
infinum/eightshift-libs pull request #397
Opened 2024-04-29 21:49 UTC by iruzevic

# Description

TBA

# Screenshots / Videos

# Linked documentation PR

# TODO
- [ ] Changelog
- [ ] Release
- [ ] Composer remove temp items
- [ ] update packages

2024-05-02 07:42 UTC, goranalkovic-infinum requested changes
Nice job!

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Helpers/ApiTrait.php
> +	 * @param string $msg Msg for the user.
```suggestion
	 * @param string $msg Message for the user.
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Helpers/ApiTrait.php
> +	 * @param string $msg Msg for the user.
```suggestion
	 * @param string $msg Message for the user.
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidPath.php
> +				\esc_html__('You are using wrong or not allowed parent path. You are using %1$s but we only allow %2$s. Please review your implementation.', 'eightshift-libs'),
```suggestion
				\esc_html__('Parent path is incorrect or not allowed. Path used: "%1$s". Allowed path: "%2$s". Please check the implementation.', 'eightshift-libs'),
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidPath.php
> +				\esc_html__('Failed to open file on this %1$s path. The file expecing should be called %2$s.', 'eightshift-libs'),
```suggestion
				\esc_html__('Failed to open the file at "%1$s". Expected file: "%2$s".', 'eightshift-libs'),
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidPath.php
> +				\esc_html__('Failed to open file on this %s path. Please check again.', 'eightshift-libs'),
```suggestion
				\esc_html__('Failed to open the file at "%s". Please check the implementation and try again.', 'eightshift-libs'),
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidPath.php
> +				\esc_html__('Failed to read directory on this %s path. Please check again.', 'eightshift-libs'),
```suggestion
				\esc_html__('Failed to read the directory at "%s". Please check the implementation and try again.', 'eightshift-libs'),
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidManifest.php
> +					'You are tryng to get manifest.json from outside of the Blocks items folder. Allowed folders are: %1$s. Path you are providing is: %2$s',
```suggestion
					'Trying to load manifest.json from outside of allowed folders. Manifest can only be loaded from: %1$s. Provided path: %2$s',
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidManifest.php
> +					'You are trying to get manifest.json outside of the Blocks folder. Please review your implementation. Path you are providing is: %s',
```suggestion
					'Trying to get manifest.json from outside of the Blocks folder. Please check your implementation. Path provided: %s',
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidManifest.php
> +					'Manifest.json in missing in %s path. Please check your data.',
```suggestion
					'Manifest missing at %s. Please verify it exists and try again.',
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidManifest.php
> +					'Manifest.json in %s path is empty or has errors. Please check your data.',
```suggestion
					'Manifest at %s is empty or has errors. Please check it and try again.',
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidManifest.php
> +					'%1$s key does not exist in manifest.json on this %2$s path. Please check if provided key is correct.',
```suggestion
					'%1$s key does not exist in manifest.json at %2$s. Please check if the provided key is correct.',
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Exception/InvalidBlock.php
> +				\esc_html__('You are trying to get %1$s %2$s. Please check if you have it in your project.', 'eightshift-libs'),
```suggestion
				\esc_html__('Trying to get %1$s %2$s. Please check if it exists in the project.', 'eightshift-libs'),
```

2024-05-02 07:42 UTC, goranalkovic-infinum commented on src/Blocks/AbstractBlocks.php
> +					},
```suggestion
					fn ($block) => $block['blockFullName'],
```

2024-05-03 11:47 UTC, piqusy requested changes
Great work 👏🏼 

Left a considerable amount of suggestions, nothing major in general captain

2024-05-03 11:47 UTC, piqusy commented on src/Cache/AbstractManifestCache.php
> +						'$schema',
```suggestion
						'$schema',
						'title',
						'description',
						'namespace',
						'blockName',
						'blockFullName',
						'keywords',
						'icon',
						'category',
```

2024-05-03 11:47 UTC, piqusy commented on src/Cache/AbstractManifestCache.php
> +						'title',
```suggestion
						'$schema',
						'title',
						'componentName',
```

2024-05-03 11:47 UTC, piqusy commented on src/Cache/AbstractManifestCache.php
> +						'description',
```suggestion
						'$schema',
						'title',
						'description',
						'icon',
						'name',
						'parentName',
```

2024-05-03 11:47 UTC, piqusy commented on src/Cache/AbstractManifestCache.php
> +						'title'
```suggestion
						'title',
```

2024-05-03 11:47 UTC, piqusy commented on src/CustomPostType/PostTypeExample.php
> +					'infobip'
```suggestion
					'eightshift-libs'
```

2024-05-03 11:47 UTC, piqusy commented on src/CustomPostType/PostTypeExample.php
> +					'infobip'
```suggestion
					'eightshift-libs'
```

2024-05-03 11:47 UTC, piqusy commented on src/CustomTaxonomy/TaxonomyExample.php
> +					'infobip'
```suggestion
					'eightshift-libs'
```

2024-05-03 11:47 UTC, piqusy commented on src/CustomTaxonomy/TaxonomyExample.php
> +					'infobip'
```suggestion
					'eightshift-libs'
```

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +					'Manifest.json in %s path is empty or has errors. Please check your data.',
I'd actually stick to `manifest.json` wording with the exception of making it start with small `m`... that is `m` as in `microoptimisation` 😄

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +	 * Throws error if manifest try to access on none allowed path.
```suggestion
	 * Throws error if trying to access manifest on non allowed path.
```

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +	 * Throws error if manifest try to access on none allowed path.
none !== non 😉

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +	 * Throws error if manifest try to access on none allowed path item.
```suggestion
	 * Throws error if trying to access manifest on non allowed path item.
```

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +				/* translators: %s is replaced by the path privided */
This line need an update

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
>  			/* translators: %s is replaced by the missing key in the manifest.json */
This line need an update

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +				/* translators: %s is replaced by the path privided */
This line need an update

2024-05-03 11:47 UTC, piqusy commented on src/Exception/InvalidManifest.php
> +				/* translators: %s is replaced by the path privided */
This line need an update

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/Helpers.php
> +		$libsPrefixedPath = ["vendor-prefixed", "infinum", "eightshift-libs"];
```suggestion
		$frontendLibsPath = ["node_modules", "@eightshift", "frontend-libs", "blocks", "init"];
		$frontendLibsPrivatePath = ["node_modules", "@eightshift", "frontend-libs-private", "blocks", "init"];
		$libsPath = ["vendor", "infinum", "eightshift-libs"];
		$libsPrefixedPath = ["vendor-prefixed", "infinum", "eightshift-libs"];

```

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/Helpers.php
> +				break;
```suggestion
				break;
```

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/Helpers.php
> +				break;
```suggestion
				break;
```

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/Helpers.php
> +				break;
```suggestion
				break;
```

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/Helpers.php
> +			case 'blocksGlobalAssetsDestination':
```suggestion
			case 'blocksGlobalAssetsDestination':
```

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/ObjectHelperTrait.php
> +	 * Get current url with params.
```suggestion
	 * Get current URL with params.
```
@goranalkovic-infinum you've missed this one 🤣

2024-05-03 11:47 UTC, piqusy commented on src/Helpers/ProjectInfoTrait.php
> +		return \wp_get_theme()->get('Version');
We are now identifying theme version with WP version?

2024-05-03 11:47 UTC, piqusy commented on src/Rest/Routes/AbstractRoute.php
> +	public const API_RESPONSE_CODE_ERROR_FORBIDDEN = 403;
Please move this up :eyetwitch:

2024-05-06 06:17 UTC, iruzevic commented on src/Helpers/Helpers.php
> +		}
no because variations doesn't have php view file so you will not be able to use ti

2024-05-06 06:43 UTC, goranalkovic-infinum commented on src/Blocks/AbstractBlocks.php
> +					},
![image](https://github.com/infinum/eightshift-libs/assets/77000136/49f42d27-179a-4cac-bb94-e50e152f428f)
😄

2024-05-06 07:50 UTC, piqusy approved these changes
Nice, found just one minuscule typo

2024-05-06 07:50 UTC, piqusy commented on src/Helpers/Helpers.php
> +	 * @param string $path Absolute path to .
```suggestion
	 * @param string $path Absolute path to.
```

2024-05-06 08:25 UTC, piqusy approved these changes

2024-05-06 11:01 UTC, merged