Cache Autowiring::buildServiceClasses into a transient
infinum/eightshift-libs pull request #440
Opened 2024-10-30 15:34 UTC by mbmjertan

# Description

Using profiling we've gathered that we spend _a lot_ of time in `Autowiring::buildServiceClasses`. In particular, we spent 14% of the whole page generation time just running the method for `EightshiftForms`.

Here's a screenshot from an Excimer-grabbed profile opened up in Speedscope on my local machine:
<img width="805" alt="Screenshot 2024-10-30 at 16 24 21" src="https://github.com/user-attachments/assets/bd57f9e3-1691-45e8-b713-bbe99d3c5ccb">

I added caching this into a transient using the project namespace as a unique key. This requires transients to be cleared on all deployments, and can cause breakage if `manuallyDefinedDependencies` is changed dynamically at runtime. This should probably be documented in eightshift-docs.

I should probably add a way to toggle this off. Do you prefer `WP_ENVIRONMENT_TYPE`, a special constant or both?

After this change, it's no longer noticeable in the profile and the whole `registerServices` method now takes less time than just the `buildServiceClasses` method used to:
<img width="1714" alt="Screenshot 2024-10-30 at 16 31 00" src="https://github.com/user-attachments/assets/94e3eb45-b551-4bf8-92b3-dedbf92e64d6">

I will open up additional PRs for optimization opportunities if I notice them.

2024-10-31 07:49 UTC, dingo-d submitted a review, later dismissed

2024-10-31 07:52 UTC, iruzevic commented
Thank you for the implementation; it’s a great idea! However, I wouldn’t make it a requirement to clear transients each time you deploy a manual thing. We already have manifest caching in the transients, along with cache busting based on the project version number and other factors. Since the Cache class is loaded before the Main class, I believe you could utilize the Cache class to get and set your transients effectively.

2024-10-31 07:53 UTC, iruzevic requested changes
I left a comment about cache busting

2024-10-31 08:54 UTC, mbmjertan commented
Awesome, I wasn't familiar with how that class was implemented! ❤️ 
I will take a look and familiarize myself with the implementation and try to utilize that.

2024-11-06 07:44 UTC, iruzevic commented
@mbmjertan and progress here, you need help?

2024-11-06 08:36 UTC, mbmjertan commented
Hi, I didn't have the time to tackle this, hopefully I will today

2024-11-08 14:37 UTC, mbmjertan commented
Refactored to use AbstractManifestCache and added basic support for caching custom objects in AbstractManifestCache (but maybe a generic concrete caching implementation in Libs would make sense in the future). Please test this before merging.

2024-11-13 14:15 UTC, mbmjertan commented
We deployed this onto staging with no issues

2024-11-22 14:08 UTC, merged