Feature/autowiring release 3
infinum/eightshift-libs pull request #83
Opened 2020-09-14 15:05 UTC by iruzevic

I have:

- [ ] fixed linting issues
- [ ] Implemented fix to exclude view files and non php files
- [ ] fixed some issues with missing names and etc.

This is tested on actual project with BP 5.0.0 and it works

2020-09-14 15:11 UTC, dingo-d commented on src/Main/AbstractMain.php
> +    return array_merge( $this->autowiring->build_service_classes(), $this->get_service_classes() );
PSR-4 it should be `buildServiceClasses()` 🤔

2020-09-14 15:11 UTC, dingo-d reviewed
Why did you replace method names to snake_case instead of camelCase?

2020-09-14 15:31 UTC, iruzevic commented on src/Main/AbstractMain.php
> +    return array_merge( $this->autowiring->build_service_classes(), $this->get_service_classes() );
fixed

2020-09-14 15:32 UTC, iruzevic commented
> Why did you replace method names to snake_case instead of camelCase?

Didn't knew about the new psr-12 standard. It is updated

2020-09-15 08:49 UTC, IvanGrginovInf requested changes
Left a single comment regarding simplifying regex, otherwise looks good.

2020-09-15 08:49 UTC, IvanGrginovInf commented on src/Main/Autowiring.php
> +			if (preg_match('/\.(php)$/', $file->getFileName()) && preg_match('/^[A-Z]{1,}.*$/m', $file->getFileName())) {
I think you should be able to do it as a single regex experssion like so (all filename starting with capital letter, ending with `.php`)

```suggestion
			if (preg_match('/[A-Z]{1}.*.php/', $file->getFileName())) {
```

2020-09-15 08:53 UTC, iruzevic commented on src/Main/Autowiring.php
> +			if (preg_match('/\.(php)$/', $file->getFileName()) && preg_match('/^[A-Z]{1,}.*$/m', $file->getFileName())) {
Tnx I have implemented the fix

2020-09-15 08:57 UTC, IvanGrginovInf approved these changes

2020-09-15 08:57 UTC, IvanGrginovInf commented
@iruzevic Approved but please fix the conflict before mering.

2020-09-15 08:58 UTC, merged