Fix lint issues
infinum/eightshift-libs pull request #84
Opened 2020-09-15 15:52 UTC by dingo-d

This is the first pass of the new linter. I fixed all of the linting issues, plus added some exceptions in the `phpcs.xml.dist`.

After this, I'll go through the PHPStan and fix the issues. I've noticed some methods that should maybe be private, some docblocs are not correct, or the type hints are missing, etc.

There are a lot of changes, but it's the only way to test the standards. Let me know if you notice anything out of place, something that was broken during the `phpcbf`, or that I missed when manually fixing the rest of the issues.

2020-09-15 21:18 UTC, iruzevic requested changes
one change but everything is ook

2020-09-15 21:18 UTC, iruzevic commented on src/Blocks/BlockCli.php
> +	 */
This method can't have doc block. Because this will automatically be shown in the WP CLI terminal as a command description and we don't want that because we have getDoc() method for this.

Please remove this

2020-09-15 21:18 UTC, iruzevic commented on src/Blocks/BlockCli.php
> +	 */
and on every __invoke method

2020-09-16 07:23 UTC, IvanGrginovInf reviewed
Left a comment regarding `array_map` otherwise looks awesome! I for one welcome our PSR-12 overlords 😄

2020-09-16 07:23 UTC, IvanGrginovInf commented on src/Blocks/AbstractBlocks.php
> +		);
Should be `foreach` because we're not returning anything.

2020-09-16 07:54 UTC, dingo-d commented on src/Blocks/BlockCli.php
> +	 */
Oh, that's unfortunate :S I'll revert this

2020-09-16 08:10 UTC, iruzevic approved these changes

2020-09-16 08:15 UTC, merged