Codeception test setup
infinum/eightshift-libs pull request #95
Opened 2020-11-17 09:10 UTC by IvanGrginovInf

2020-11-17 09:13 UTC, dingo-d approved these changes

2020-11-17 09:29 UTC, iruzevic approved these changes

2020-11-23 09:19 UTC, dingo-d commented on composer.json
>  		"standards:fix": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcbf",
Why is this line indented weirdly?

2020-11-23 09:21 UTC, dingo-d commented on composer.json
> +  "minimum-stability": "dev",
`autoload-dev` should be added for tests as well, something like

```json
"autoload-dev": {
    "psr-4": {
        "Tests\\": "tests/",
    }
},
```

2020-11-23 09:22 UTC, dingo-d requested changes
Left a comment

2020-11-23 10:04 UTC, IvanGrginovInf commented on composer.json
>  		"standards:fix": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcbf",
I fixed this already (tabs instead of spaces) 🙈 will fix

2020-11-23 12:08 UTC, iruzevic approved these changes

2020-11-23 21:56 UTC, dingo-d approved these changes

2020-11-25 08:51 UTC, merged